import { Component, Input, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ProductInfo } from '../core/models';

interface DwcMember { id:string; name:string; role:string; joined:string; status:string; leadershipInterest:boolean; careStatus:string; }
interface DwcAssignment { id:string; title:string; owner:string; scope:string; meeting:string; status:string; }
interface DwcMeeting { id:string; date:string; time:string; topic:string; location:string; attendance:string[]; }
interface DwcResource { id:string; title:string; type:string; status:string; }
interface DwcGroup { id:string; name:string; cluster:string; leader:string; coLeader:string; apprentice:string; host:string; day:string; time:string; area:string; format:string; audience:string; childcare:boolean; capacity:number; status:string; semester:string; curriculum:string; members:DwcMember[]; assignments:DwcAssignment[]; meetings:DwcMeeting[]; resources:DwcResource[]; }
interface DwcPlacement { id:string; name:string; interest:string; preferredDay:string; area:string; suggestedGroup:string; status:string; note:string; }
interface DwcCluster { id:string; name:string; leader:string; groupIds:string[]; }
interface DwcSemester { id:string; name:string; starts:string; ends:string; status:string; }
interface DwcState { groups:DwcGroup[]; placements:DwcPlacement[]; clusters:DwcCluster[]; semesters:DwcSemester[]; }

const SEED:DwcState={
  semesters:[
    {id:'spring-2027',name:'Spring 2027',starts:'January 18, 2027',ends:'May 16, 2027',status:'Current'},
    {id:'summer-2027',name:'Summer 2027',starts:'June 7, 2027',ends:'August 15, 2027',status:'Planning'},
    {id:'fall-2026',name:'Fall 2026',starts:'September 8, 2026',ends:'December 13, 2026',status:'Archived'}
  ],
  clusters:[
    {id:'central',name:'Central Cluster',leader:'Alicia Brown',groupIds:['young-adults','women-purpose']},
    {id:'east',name:'East Cluster',leader:'Marcus Hill',groupIds:['marriage-family','young-families']},
    {id:'south',name:'South Cluster',leader:'James Carter',groupIds:['men-valor','purpose-career']}
  ],
  placements:[
    {id:'p1',name:'Michael Turner',interest:'Young adults / spiritual growth',preferredDay:'Wednesday',area:'Richmond Central',suggestedGroup:'Young Adults DEG',status:'New',note:'Recently completed new member orientation.'},
    {id:'p2',name:'Danielle Brooks',interest:'Women / discipleship',preferredDay:'Wednesday',area:'Richmond Central',suggestedGroup:'Women of Purpose',status:'Leader review',note:'Requested childcare information.'},
    {id:'p3',name:'Anthony Lewis',interest:'Men / leadership',preferredDay:'Monday',area:'Richmond South',suggestedGroup:'Men of Valor',status:'New',note:'Interested in serving and leadership development.'},
    {id:'p4',name:'Tiffany & Aaron Reed',interest:'Marriage & family',preferredDay:'Wednesday',area:'Richmond East',suggestedGroup:'Marriage & Family',status:'Waitlist',note:'Group is currently at capacity; suggested Young Families as alternate.'}
  ],
  groups:[
    {id:'young-adults',name:'Young Adults DEG',cluster:'Central Cluster',leader:'Alicia Brown',coLeader:'Michael Turner',apprentice:'Jordan Davis',host:'Carter Family',day:'Wednesday',time:'6:30 PM',area:'Richmond Central',format:'In person',audience:'Young Adults',childcare:false,capacity:15,status:'Open',semester:'Spring 2027',curriculum:'Divine Transformation Track 1',
      members:[
        {id:'m1',name:'Michael Turner',role:'Co-Leader',joined:'Jan 2027',status:'Active',leadershipInterest:true,careStatus:'None'},
        {id:'m2',name:'Jordan Davis',role:'Apprentice Leader',joined:'Jan 2027',status:'Active',leadershipInterest:true,careStatus:'None'},
        {id:'m3',name:'Sarah Jones',role:'Member',joined:'Feb 2027',status:'Active',leadershipInterest:false,careStatus:'Follow-up underway'},
        {id:'m4',name:'Andre Lewis',role:'Member',joined:'Jan 2027',status:'Active',leadershipInterest:false,careStatus:'None'},
        {id:'m5',name:'Kayla Martin',role:'Member',joined:'Jan 2027',status:'Active',leadershipInterest:false,careStatus:'None'},
        {id:'m6',name:'Devin Brooks',role:'Member',joined:'Mar 2027',status:'Active',leadershipInterest:false,careStatus:'None'},
        {id:'m7',name:'Jasmine Reed',role:'Member',joined:'Jan 2027',status:'Active',leadershipInterest:true,careStatus:'None'},
        {id:'m8',name:'Tyler Moore',role:'Member',joined:'Feb 2027',status:'Active',leadershipInterest:false,careStatus:'None'},
        {id:'m9',name:'Brianna Hill',role:'Member',joined:'Jan 2027',status:'Active',leadershipInterest:false,careStatus:'None'},
        {id:'m10',name:'Chris Allen',role:'Member',joined:'Jan 2027',status:'Active',leadershipInterest:false,careStatus:'None'},
        {id:'m11',name:'Nia Carter',role:'Member',joined:'Mar 2027',status:'Active',leadershipInterest:false,careStatus:'None'}
      ],
      assignments:[
        {id:'a1',title:'Facilitator',owner:'Alicia Brown',scope:'Meeting',meeting:'Apr 21',status:'Assigned'},
        {id:'a2',title:'Opening Prayer',owner:'Jordan Davis',scope:'Meeting',meeting:'Apr 21',status:'Assigned'},
        {id:'a3',title:'Hospitality',owner:'Carter Family',scope:'Recurring',meeting:'Every meeting',status:'Assigned'},
        {id:'a4',title:'Refreshments',owner:'',scope:'Meeting',meeting:'Apr 21',status:'Open'},
        {id:'a5',title:'Follow-up',owner:'Michael Turner',scope:'Recurring',meeting:'Weekly',status:'Assigned'}
      ],
      meetings:[
        {id:'meet1',date:'Apr 14',time:'6:30 PM',topic:'Identity & Calling',location:'Carter Home',attendance:['m1','m2','m3','m4','m5','m7','m8','m9','m10']},
        {id:'meet2',date:'Apr 21',time:'6:30 PM',topic:'Discipline & Devotion',location:'Carter Home',attendance:[]}
      ],
      resources:[{id:'r1',title:'Divine Transformation Track 1 — Week 5',type:'Curriculum',status:'Published'},{id:'r2',title:'Discussion Guide',type:'Leader resource',status:'Published'},{id:'r3',title:'Prayer & Reflection Guide',type:'Member resource',status:'Published'}]},
    {id:'marriage-family',name:'Marriage & Family',cluster:'East Cluster',leader:'Marcus Hill',coLeader:'Jordan Hill',apprentice:'',host:'Hill Family',day:'Wednesday',time:'6:30 PM',area:'Richmond East',format:'In person',audience:'Married Couples',childcare:true,capacity:14,status:'Full',semester:'Spring 2027',curriculum:'Kingdom Marriage Foundations',members:Array.from({length:14},(_,i)=>({id:`mf${i+1}`,name:['Marcus Hill','Jordan Hill','James Carter','Ashley Carter','David Green','Monica Green','Aaron Reed','Tiffany Reed','Caleb Wright','Nicole Wright','Darius King','Maya King','Steven Hall','Renee Hall'][i],role:i===0?'Group Leader':i===1?'Co-Leader':'Member',joined:'Jan 2027',status:'Active',leadershipInterest:i===2,careStatus:'None'})),assignments:[{id:'ma1',title:'Discussion Lead',owner:'Marcus Hill',scope:'Recurring',meeting:'Weekly',status:'Assigned'},{id:'ma2',title:'Childcare Coordinator',owner:'Ashley Carter',scope:'Recurring',meeting:'Weekly',status:'Assigned'}],meetings:[{id:'mm1',date:'Apr 21',time:'6:30 PM',topic:'Communication & Covenant',location:'Hill Home',attendance:[]}],resources:[{id:'mr1',title:'Kingdom Marriage — Session 6',type:'Curriculum',status:'Published'}]},
    {id:'men-valor',name:'Men of Valor',cluster:'South Cluster',leader:'James Carter',coLeader:'',apprentice:'Anthony Lewis',host:'King Center',day:'Monday',time:'6:30 PM',area:'Richmond South',format:'In person',audience:'Men',childcare:false,capacity:12,status:'Open',semester:'Spring 2027',curriculum:'Manhood, Prayer & Purpose',members:Array.from({length:8},(_,i)=>({id:`mv${i+1}`,name:['James Carter','Anthony Lewis','Devon Price','Malik Brown','Terrence Cole','Isaiah Moore','Robert King','Nathan Hall'][i],role:i===0?'Group Leader':i===1?'Apprentice Leader':'Member',joined:'Jan 2027',status:'Active',leadershipInterest:i===1,careStatus:'None'})),assignments:[{id:'mva1',title:'Prayer Lead',owner:'Anthony Lewis',scope:'Recurring',meeting:'Weekly',status:'Assigned'}],meetings:[{id:'mvm1',date:'Apr 19',time:'6:30 PM',topic:'Purpose & Responsibility',location:'King Center',attendance:[]}],resources:[{id:'mvr1',title:'Manhood, Prayer & Purpose — Week 7',type:'Curriculum',status:'Published'}]},
    {id:'women-purpose',name:'Women of Purpose',cluster:'Central Cluster',leader:'Jordan Davis',coLeader:'Nia Carter',apprentice:'',host:'Divine World Changers',day:'Wednesday',time:'6:30 PM',area:'Richmond Central',format:'Hybrid',audience:'Women',childcare:true,capacity:15,status:'Nearly Full',semester:'Spring 2027',curriculum:'Identity & Purpose',members:Array.from({length:13},(_,i)=>({id:`wp${i+1}`,name:['Jordan Davis','Nia Carter','Danielle Brooks','Lisa James','Monique Reed','Tasha Brown','Ashley Hall','Keisha Moore','Brittany Cole','Vanessa Wright','Erica King','Tina Lewis','Crystal Martin'][i],role:i===0?'Group Leader':i===1?'Co-Leader':'Member',joined:'Jan 2027',status:'Active',leadershipInterest:i===1,careStatus:i===2?'Prayer requested':'None'})),assignments:[{id:'wpa1',title:'Communications',owner:'Nia Carter',scope:'Recurring',meeting:'Weekly',status:'Assigned'}],meetings:[{id:'wpm1',date:'Apr 21',time:'6:30 PM',topic:'Identity & Purpose',location:'DWC Classroom 2',attendance:[]}],resources:[{id:'wpr1',title:'Identity & Purpose — Week 5',type:'Curriculum',status:'Published'}]},
    {id:'young-families',name:'Young Families',cluster:'East Cluster',leader:'Monica Green',coLeader:'David Green',apprentice:'',host:'Green Home',day:'Monday',time:'6:30 PM',area:'Richmond East',format:'In person',audience:'Young Families',childcare:true,capacity:15,status:'Open',semester:'Spring 2027',curriculum:'Building a Kingdom Home',members:Array.from({length:10},(_,i)=>({id:`yf${i+1}`,name:`Young Family Member ${i+1}`,role:i===0?'Group Leader':i===1?'Co-Leader':'Member',joined:'Jan 2027',status:'Active',leadershipInterest:false,careStatus:'None'})),assignments:[],meetings:[{id:'yfm1',date:'Apr 19',time:'6:30 PM',topic:'Rhythms at Home',location:'Green Home',attendance:[]}],resources:[{id:'yfr1',title:'Building a Kingdom Home — Week 4',type:'Curriculum',status:'Published'}]},
    {id:'purpose-career',name:'Purpose & Career',cluster:'South Cluster',leader:'Alicia Brown',coLeader:'',apprentice:'',host:'Divine World Changers',day:'Thursday',time:'7:00 PM',area:'Richmond South',format:'Hybrid',audience:'Adults',childcare:false,capacity:12,status:'Open',semester:'Spring 2027',curriculum:'Purpose in the Marketplace',members:Array.from({length:7},(_,i)=>({id:`pc${i+1}`,name:`Purpose Member ${i+1}`,role:i===0?'Group Leader':'Member',joined:'Feb 2027',status:'Active',leadershipInterest:false,careStatus:'None'})),assignments:[],meetings:[{id:'pcm1',date:'Apr 22',time:'7:00 PM',topic:'Work as Worship',location:'DWC Conference Room',attendance:[]}],resources:[{id:'pcr1',title:'Purpose in the Marketplace — Week 3',type:'Curriculum',status:'Published'}]}
  ]
};

@Component({
  selector:'app-dwc-space',
  standalone:true,
  imports:[FormsModule],
  template:`
  <section class="org-space" style="--org-accent:#6b4fa1;--org-soft:#f3eefb">
    <header class="org-hero">
      <div><p class="org-eyebrow">Divine World Changers · Engagements</p><h1>Divine Empowerment Groups</h1><p>Operate every semester, cluster, group, leader assignment, roster, meeting, placement request, and follow-up from one source of truth.</p></div>
      <div class="org-hero__actions"><button class="org-button org-button--outline" type="button" (click)="section.set('public')">Public directory</button><button class="org-button org-button--primary" type="button" (click)="openCreate()">Create group</button></div>
    </header>

    <nav class="org-tabs" aria-label="Divine Empowerment Groups">
      @for(tab of tabs;track tab.key){<button type="button" [class.active]="section()===tab.key" (click)="section.set(tab.key)">{{tab.label}}</button>}
    </nav>

    @switch(section()){
      @case('overview'){
        <div class="org-grid">
          <article class="org-surface org-pad org-span-12"><div class="org-metrics"><div class="org-metric"><span>Active groups</span><strong>{{activeGroups()}}</strong><small>Spring 2027</small></div><div class="org-metric"><span>Enrolled</span><strong>{{enrolled()}}</strong><small>Across all active groups</small></div><div class="org-metric"><span>Open seats</span><strong>{{openSeats()}}</strong><small>Available now</small></div><div class="org-metric"><span>Placement queue</span><strong>{{openPlacements()}}</strong><small>Need a decision</small></div><div class="org-metric"><span>Cluster leaders</span><strong>{{state().clusters.length}}</strong><small>Oversight scopes</small></div></div></article>
          <article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">Needs attention</p><h2>Group command center</h2><p>The executive team can see where capacity, assignments, attendance, or care follow-up needs a human.</p></div><button class="org-button" type="button" (click)="section.set('groups')">All groups</button></header><div class="org-command-list"><div class="org-command"><span>01</span><div><strong>Marriage & Family is full</strong><p>14 of 14 seats filled. One household is waiting for placement.</p></div><button class="org-button" type="button" (click)="section.set('placements')">Resolve</button></div><div class="org-command"><span>02</span><div><strong>Young Adults has an open meeting assignment</strong><p>Refreshments for Apr 21 still needs an owner.</p></div><button class="org-button" type="button" (click)="openGroup('young-adults','assignments')">Assign</button></div><div class="org-command"><span>03</span><div><strong>Two member care signals are active</strong><p>Engagements shows status only; sensitive details remain in Care.</p></div><a class="org-button" [href]="product.careUrl">Open Care</a></div><div class="org-command"><span>04</span><div><strong>Summer semester planning is open</strong><p>Carry forward leaders, update capacity, curriculum, and meeting patterns.</p></div><button class="org-button" type="button" (click)="section.set('semesters')">Plan</button></div></div></article>
          <aside class="org-surface org-pad org-span-4"><header class="org-section-head"><div><p class="org-eyebrow">Current semester</p><h3>Spring 2027</h3></div><span class="org-status org-status--good">Active</span></header><div class="org-list"><div class="org-list-row"><div><strong>January 18 – May 16</strong><p>Six active groups across three clusters.</p></div></div><div class="org-list-row"><div><strong>Leader training</strong><p>14 of 16 required leader completions recorded.</p></div><a class="org-link" [href]="product.academyUrl">Academy ↗</a></div><div class="org-list-row"><div><strong>Calendar sync</strong><p>Group meetings publish into the organization calendar without exposing private rosters.</p></div><a class="org-link" [href]="product.platformUrl">Platform ↗</a></div></div></aside>
          <article class="org-surface org-pad org-span-7"><header class="org-section-head"><div><p class="org-eyebrow">Capacity</p><h2>Where people can still join</h2></div></header><div class="org-kpi-bars">@for(g of state().groups;track g.id){<div><div class="org-kpi-bar__top"><span>{{g.name}}</span><strong>{{g.members.length}} / {{g.capacity}}</strong></div><div class="org-progress"><span [style.width.%]="capacityPercent(g)"></span></div></div>}</div></article>
          <aside class="org-surface org-pad org-span-5"><header class="org-section-head"><div><p class="org-eyebrow">Platform connections</p><h3>One operating system</h3></div></header><div class="org-module-links"><a class="org-module-link" [href]="product.peopleUrl"><strong>People</strong><span>Member records</span></a><a class="org-module-link" [href]="product.careUrl"><strong>Care</strong><span>Pastoral follow-up</span></a><a class="org-module-link" [href]="product.academyUrl"><strong>Academy</strong><span>Leader training</span></a><a class="org-module-link" [href]="product.operationsUrl"><strong>Operations</strong><span>Shared work</span></a><a class="org-module-link" [href]="product.impactUrl"><strong>Impact</strong><span>Participation health</span></a></div></aside>
        </div>
      }
      @case('groups'){
        <article class="org-surface org-pad"><header class="org-section-head"><div><p class="org-eyebrow">Spring 2027</p><h2>Group directory</h2><p>Filter by cluster, availability, audience, meeting day, or area.</p></div><button class="org-button org-button--primary" type="button" (click)="openCreate()">Create group</button></header><div class="org-toolbar"><input placeholder="Search groups, leaders, areas" [(ngModel)]="search"><select [(ngModel)]="clusterFilter"><option value="">All clusters</option>@for(c of state().clusters;track c.id){<option [value]="c.name">{{c.name}}</option>}</select><select [(ngModel)]="statusFilter"><option value="">All statuses</option><option>Open</option><option>Nearly Full</option><option>Full</option><option>Waitlist</option><option>Paused</option></select></div><div class="org-table-wrap"><table class="org-table"><thead><tr><th>Group</th><th>Cluster</th><th>Leader</th><th>Meets</th><th>Area</th><th>Members</th><th>Status</th></tr></thead><tbody>@for(g of filteredGroups();track g.id){<tr data-clickable (click)="openGroup(g.id,'overview')"><td><strong>{{g.name}}</strong><br><small>{{g.audience}} · {{g.format}}</small></td><td>{{g.cluster}}</td><td>{{g.leader}}</td><td>{{g.day}} · {{g.time}}</td><td>{{g.area}}</td><td>{{g.members.length}} / {{g.capacity}}</td><td><span class="org-status" [class.org-status--good]="g.status==='Open'" [class.org-status--warn]="g.status==='Nearly Full'" [class.org-status--bad]="g.status==='Full'">{{g.status}}</span></td></tr>}</tbody></table></div></article>
      }
      @case('placements'){
        <div class="org-grid"><article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">Join requests</p><h2>Placement queue</h2><p>Match people to the right group without sharing private roster information publicly.</p></div></header><div class="org-list">@for(p of state().placements;track p.id){<div class="org-list-row"><div><strong>{{p.name}}</strong><p>{{p.interest}} · {{p.preferredDay}} · {{p.area}}</p><small>Suggested: {{p.suggestedGroup}} · {{p.note}}</small></div><div class="org-actions"><span class="org-status">{{p.status}}</span>@if(p.status!=='Placed'){<button class="org-button" type="button" (click)="updatePlacement(p.id,'Leader review')">Send to leader</button><button class="org-button org-button--primary" type="button" (click)="placeRequest(p)">Place</button>}</div></div>}</div></article><aside class="org-surface org-pad org-span-4"><p class="org-eyebrow">Placement workflow</p><h3>From interest to belonging</h3><div class="org-timeline"><div class="org-timeline-item"><small>1</small><strong>Request received</strong><p>Preferences and life stage captured.</p></div><div class="org-timeline-item"><small>2</small><strong>Coordinator reviews</strong><p>Capacity and fit checked.</p></div><div class="org-timeline-item"><small>3</small><strong>Leader notified</strong><p>Leader confirms relational fit.</p></div><div class="org-timeline-item"><small>4</small><strong>Placed / waitlisted</strong><p>People record is linked to the roster.</p></div></div></aside></div>
      }
      @case('clusters'){
        <div class="org-card-grid">@for(c of state().clusters;track c.id){<article class="org-card"><p class="org-eyebrow">{{c.name}}</p><h3>{{c.leader}}</h3><p>Cluster Leader · {{c.groupIds.length}} groups · {{clusterMembers(c)}} enrolled</p><div class="org-list">@for(gid of c.groupIds;track gid){@if(groupById(gid);as g){<div class="org-list-row"><div><strong>{{g.name}}</strong><p>{{g.members.length}}/{{g.capacity}} · {{g.status}}</p></div><button class="org-button" type="button" (click)="openGroup(g.id,'overview')">Open</button></div>}}</div><footer><span>{{clusterOpenSeats(c)}} open seats</span><span class="org-status org-status--accent">Scoped oversight</span></footer></article>}</div>
      }
      @case('semesters'){
        <div class="org-grid"><article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">Semester management</p><h2>Program cycles</h2><p>History stays intact while leaders, schedules, capacity, and curriculum can roll forward.</p></div><button class="org-button org-button--primary" type="button" (click)="rolloverSemester()">Prepare Summer 2027</button></header><div class="org-list">@for(s of state().semesters;track s.id){<div class="org-list-row"><div><strong>{{s.name}}</strong><p>{{s.starts}} – {{s.ends}}</p></div><span class="org-status" [class.org-status--good]="s.status==='Current'">{{s.status}}</span></div>}</div></article><aside class="org-surface org-pad org-span-4"><p class="org-eyebrow">Rollover checklist</p><h3>Summer 2027</h3><div class="org-list"><div class="org-list-row"><div><strong>Keep active groups</strong><p>6 current structures available to carry forward.</p></div><span>✓</span></div><div class="org-list-row"><div><strong>Confirm leader teams</strong><p>Leader, co-leader, apprentice, host.</p></div><span>✓</span></div><div class="org-list-row"><div><strong>Set capacity & schedule</strong><p>Update meeting patterns before publishing.</p></div><span>○</span></div><div class="org-list-row"><div><strong>Invite re-enrollment</strong><p>Members opt into the next semester.</p></div><span>○</span></div></div></aside></div>
      }
      @case('my-group'){
        <div class="org-grid"><article class="org-surface org-pad org-span-8"><p class="org-eyebrow">My Group</p><h2>Young Adults DEG</h2><p class="org-callout"><strong>Next meeting:</strong> Wednesday · 6:30 PM · Carter Home. Topic: Discipline & Devotion.</p><div class="org-card-grid" style="margin-top:14px"><div class="org-card"><h3>My assignment</h3><p>Jordan Davis · Opening Prayer · Apr 21</p></div><div class="org-card"><h3>Current resource</h3><p>Divine Transformation Track 1 — Week 5</p></div><div class="org-card"><h3>Group contact</h3><p>Alicia Brown · Group Leader</p></div></div></article><aside class="org-surface org-pad org-span-4"><p class="org-eyebrow">Member experience</p><h3>Simple by design</h3><p class="org-callout">Members see meetings, assignments, announcements, resources, attendance/check-in, and a way to request care. They do not see internal staff notes or other members' private records.</p><button class="org-button org-button--primary" style="margin-top:12px" type="button" (click)="openGroup('young-adults','resources')">Open resources</button></aside></div>
      }
      @case('public'){
        <div class="org-public-preview"><p class="org-eyebrow">Website-ready public feed</p><h2>Find a Divine Empowerment Group</h2><p>This safe directory can feed the DWC public website. It publishes availability and meeting information without exposing rosters, care data, or private addresses.</p><div class="org-card-grid">@for(g of state().groups;track g.id){<article class="org-card"><h3>{{g.name}}</h3><p>{{g.audience}} · {{g.day}} · {{g.time}}<br>{{g.area}} · {{g.format}}</p><footer><span>{{publicAvailability(g)}}</span><button class="org-button org-button--primary" type="button" (click)="requestJoin(g)">Request to join</button></footer></article>}</div></div>
      }
      @case('analytics'){
        <div class="org-grid"><article class="org-surface org-pad org-span-7"><header class="org-section-head"><div><p class="org-eyebrow">Group health</p><h2>Engagement & growth</h2></div><a class="org-link" [href]="product.impactUrl">Open Impact ↗</a></header><div class="org-metrics"><div class="org-metric"><span>Avg capacity</span><strong>{{averageCapacity()}}%</strong></div><div class="org-metric"><span>Attendance</span><strong>84%</strong></div><div class="org-metric"><span>Re-enroll intent</span><strong>78%</strong></div><div class="org-metric"><span>Emerging leaders</span><strong>{{leadershipCandidates()}}</strong></div><div class="org-metric"><span>Care signals</span><strong>{{careSignals()}}</strong></div></div><div class="org-callout" style="margin-top:14px">Impact owns long-term reporting. Engagements supplies participation, capacity, attendance, placement, and leadership-development events without duplicating pastoral records.</div></article><aside class="org-surface org-pad org-span-5"><p class="org-eyebrow">Cross-module integrations</p><h3>Governed handoffs</h3><div class="org-list"><div class="org-list-row"><div><strong>People</strong><p>One person record across every group and semester.</p></div></div><div class="org-list-row"><div><strong>Care</strong><p>Only status returns to group leaders; sensitive notes stay private.</p></div></div><div class="org-list-row"><div><strong>Academy</strong><p>Leader requirements and transformation tracks.</p></div></div><div class="org-list-row"><div><strong>Platform Calendar</strong><p>Group meetings publish with privacy-safe metadata.</p></div></div><div class="org-list-row"><div><strong>Communications</strong><p>Placement, meeting, assignment, and re-enrollment notices.</p></div></div></div></aside></div>
      }
    }

    @if(selectedGroup();as g){<button class="org-drawer-scrim" type="button" aria-label="Close group" (click)="closeDrawer()"></button><aside class="org-drawer"><header><div><p>{{g.cluster}} · {{g.semester}}</p><h2>{{g.name}}</h2></div><button class="org-close" type="button" (click)="closeDrawer()">×</button></header><div class="org-drawer__body"><div class="org-drawer-tabs">@for(tab of groupTabs;track tab){<button type="button" [class.active]="groupTab()===tab" (click)="groupTab.set(tab)">{{tab}}</button>}</div>@switch(groupTab()){
      @case('overview'){<div class="org-form-grid"><div class="org-callout"><strong>Leader</strong><br>{{g.leader}}<br><small>Co-Leader: {{g.coLeader||'Open'}}</small></div><div class="org-callout"><strong>Apprentice</strong><br>{{g.apprentice||'Not assigned'}}<br><small>Host: {{g.host}}</small></div><div class="org-callout"><strong>Meeting</strong><br>{{g.day}} · {{g.time}}<br><small>{{g.area}} · {{g.format}}</small></div><div class="org-callout"><strong>Capacity</strong><br>{{g.members.length}} / {{g.capacity}}<br><small>{{g.status}}</small></div></div><p class="org-eyebrow" style="margin-top:18px">Curriculum</p><h3>{{g.curriculum}}</h3><div class="org-actions" style="margin-top:15px"><button class="org-button" type="button" (click)="editGroup(g)">Edit group</button><a class="org-button" [href]="product.peopleUrl">Open linked People</a></div>}
      @case('people'){<div class="org-table-wrap"><table class="org-table"><thead><tr><th>Name</th><th>Role</th><th>Joined</th><th>Care</th><th>Leadership</th></tr></thead><tbody>@for(m of g.members;track m.id){<tr><td><strong>{{m.name}}</strong></td><td>{{m.role}}</td><td>{{m.joined}}</td><td>{{m.careStatus}}</td><td>{{m.leadershipInterest?'Candidate':'—'}}</td></tr>}</tbody></table></div>}
      @case('meetings'){<div class="org-list">@for(meeting of g.meetings;track meeting.id){<div class="org-list-row"><div><strong>{{meeting.date}} · {{meeting.time}}</strong><p>{{meeting.topic}} · {{meeting.location}}</p></div><span class="org-status">{{meeting.attendance.length}} attended</span></div>}@if(g.meetings.length){<p class="org-eyebrow" style="margin-top:14px">Take attendance · {{g.meetings[g.meetings.length-1].date}}</p><div class="org-attendance">@for(m of g.members;track m.id){<button type="button" [class.present]="isPresent(g,m.id)" (click)="toggleAttendance(g.id,m.id)"><span>{{m.name}}</span><span>{{isPresent(g,m.id)?'✓':'○'}}</span></button>}</div>}</div>}
      @case('assignments'){<div class="org-list">@for(a of g.assignments;track a.id){<div class="org-list-row"><div><strong>{{a.title}}</strong><p>{{a.scope}} · {{a.meeting}}</p></div><div class="org-actions"><span class="org-status" [class.org-status--warn]="!a.owner">{{a.owner||'Needs owner'}}</span>@if(!a.owner){<button class="org-button" type="button" (click)="claimAssignment(g.id,a.id)">Assign Jordan</button>}</div></div>}</div>}
      @case('care'){<div class="org-callout"><strong>Privacy boundary:</strong> group leaders see that follow-up exists, who owns the next step, and whether it is complete. Pastoral notes and sensitive details remain in Care.</div><div class="org-list" style="margin-top:12px">@for(m of g.members;track m.id){@if(m.careStatus!=='None'){<div class="org-list-row"><div><strong>{{m.name}}</strong><p>{{m.careStatus}}</p></div><a class="org-button" [href]="product.careUrl">Open Care</a></div>}}</div>}
      @case('resources'){<div class="org-list">@for(r of g.resources;track r.id){<div class="org-list-row"><div><strong>{{r.title}}</strong><p>{{r.type}}</p></div><span class="org-status org-status--good">{{r.status}}</span></div>}</div><div class="org-callout" style="margin-top:14px">Academy remains the system of record for formal training. Group resources can link to Academy courses without duplicating progress.</div>}
    }</div></aside>}

    @if(groupDraft();as draft){<button class="org-drawer-scrim" type="button" aria-label="Close editor" (click)="groupDraft.set(null)"></button><aside class="org-drawer"><header><div><p>Divine Empowerment Groups</p><h2>{{draft.id?'Edit group':'Create group'}}</h2></div><button class="org-close" type="button" (click)="groupDraft.set(null)">×</button></header><div class="org-drawer__body"><div class="org-form"><label class="org-field"><span>Group name</span><input [(ngModel)]="draft.name"></label><div class="org-form-grid"><label class="org-field"><span>Cluster</span><select [(ngModel)]="draft.cluster">@for(c of state().clusters;track c.id){<option [value]="c.name">{{c.name}}</option>}</select></label><label class="org-field"><span>Status</span><select [(ngModel)]="draft.status"><option>Open</option><option>Nearly Full</option><option>Full</option><option>Waitlist</option><option>Paused</option></select></label></div><div class="org-form-grid"><label class="org-field"><span>Leader</span><input [(ngModel)]="draft.leader"></label><label class="org-field"><span>Co-Leader</span><input [(ngModel)]="draft.coLeader"></label></div><div class="org-form-grid"><label class="org-field"><span>Apprentice leader</span><input [(ngModel)]="draft.apprentice"></label><label class="org-field"><span>Host</span><input [(ngModel)]="draft.host"></label></div><div class="org-form-grid"><label class="org-field"><span>Meeting day</span><input [(ngModel)]="draft.day"></label><label class="org-field"><span>Time</span><input [(ngModel)]="draft.time"></label></div><div class="org-form-grid"><label class="org-field"><span>General area</span><input [(ngModel)]="draft.area"></label><label class="org-field"><span>Capacity</span><input type="number" [(ngModel)]="draft.capacity"></label></div><div class="org-form-grid"><label class="org-field"><span>Audience</span><input [(ngModel)]="draft.audience"></label><label class="org-field"><span>Format</span><select [(ngModel)]="draft.format"><option>In person</option><option>Hybrid</option><option>Virtual</option></select></label></div><label class="org-field"><span>Curriculum</span><input [(ngModel)]="draft.curriculum"></label><label class="org-checkbox"><input type="checkbox" [(ngModel)]="draft.childcare">Childcare available</label></div><footer class="org-drawer-footer"><button class="org-button" type="button" (click)="groupDraft.set(null)">Cancel</button><button class="org-button org-button--primary" type="button" (click)="saveGroup(draft)">Save group</button></footer></div></aside>}
  </section>`,
  styleUrl:'./organization-space.scss'
})
export class DwcSpaceComponent{
  @Input({required:true}) product!:ProductInfo;
  readonly tabs=[{key:'overview',label:'Overview'},{key:'groups',label:'Groups'},{key:'placements',label:'Placement'},{key:'clusters',label:'Clusters'},{key:'semesters',label:'Semesters'},{key:'my-group',label:'My Group'},{key:'analytics',label:'Impact & integrations'}] as const;
  readonly groupTabs=['overview','people','meetings','assignments','care','resources'] as const;
  readonly section=signal<string>('overview');
  readonly groupTab=signal<string>('overview');
  readonly state=signal<DwcState>(this.load());
  readonly selectedGroupId=signal<string|null>(null);
  readonly groupDraft=signal<DwcGroup|null>(null);
  search='';clusterFilter='';statusFilter='';

  private load():DwcState{try{const raw=localStorage.getItem('apostolos.engagements.dwc.deg.v1');return raw?JSON.parse(raw) as DwcState:structuredClone(SEED);}catch{return structuredClone(SEED)}}
  private persist(next:DwcState){this.state.set(next);try{localStorage.setItem('apostolos.engagements.dwc.deg.v1',JSON.stringify(next));}catch{}}
  activeGroups(){return this.state().groups.filter(g=>g.status!=='Paused').length}
  enrolled(){return this.state().groups.reduce((sum,g)=>sum+g.members.length,0)}
  openSeats(){return this.state().groups.reduce((sum,g)=>sum+Math.max(g.capacity-g.members.length,0),0)}
  openPlacements(){return this.state().placements.filter(p=>p.status!=='Placed').length}
  leadershipCandidates(){return this.state().groups.flatMap(g=>g.members).filter(m=>m.leadershipInterest).length}
  careSignals(){return this.state().groups.flatMap(g=>g.members).filter(m=>m.careStatus!=='None').length}
  averageCapacity(){const groups=this.state().groups;return groups.length?Math.round(groups.reduce((s,g)=>s+this.capacityPercent(g),0)/groups.length):0}
  capacityPercent(g:DwcGroup){return Math.min(100,Math.round(g.members.length*100/g.capacity))}
  publicAvailability(g:DwcGroup){const open=g.capacity-g.members.length;return open<=0?'Waitlist':open===1?'1 space available':`${open} spaces available`}
  filteredGroups(){const q=this.search.trim().toLowerCase();return this.state().groups.filter(g=>(!q||`${g.name} ${g.leader} ${g.area} ${g.audience}`.toLowerCase().includes(q))&&(!this.clusterFilter||g.cluster===this.clusterFilter)&&(!this.statusFilter||g.status===this.statusFilter))}
  groupById(id:string){return this.state().groups.find(g=>g.id===id)}
  selectedGroup(){const id=this.selectedGroupId();return id?this.groupById(id):undefined}
  openGroup(id:string,tab:string){this.selectedGroupId.set(id);this.groupTab.set(tab)}
  closeDrawer(){this.selectedGroupId.set(null)}
  clusterMembers(c:DwcCluster){return c.groupIds.reduce((s,id)=>s+(this.groupById(id)?.members.length??0),0)}
  clusterOpenSeats(c:DwcCluster){return c.groupIds.reduce((s,id)=>{const g=this.groupById(id);return s+(g?Math.max(g.capacity-g.members.length,0):0)},0)}
  openCreate(){this.groupDraft.set({id:'',name:'',cluster:this.state().clusters[0]?.name??'',leader:'',coLeader:'',apprentice:'',host:'',day:'Wednesday',time:'6:30 PM',area:'Richmond',format:'In person',audience:'Adults',childcare:false,capacity:12,status:'Open',semester:'Spring 2027',curriculum:'',members:[],assignments:[],meetings:[],resources:[]})}
  editGroup(g:DwcGroup){this.selectedGroupId.set(null);this.groupDraft.set(structuredClone(g))}
  saveGroup(draft:DwcGroup){if(!draft.name.trim())return;const next=structuredClone(this.state());if(draft.id){const index=next.groups.findIndex(g=>g.id===draft.id);if(index>=0)next.groups[index]=structuredClone(draft);}else{draft.id=`group-${Date.now()}`;next.groups.push(structuredClone(draft));const cluster=next.clusters.find(c=>c.name===draft.cluster);if(cluster)cluster.groupIds.push(draft.id)}this.persist(next);this.groupDraft.set(null)}
  isPresent(g:DwcGroup,memberId:string){const meeting=g.meetings[g.meetings.length-1];return meeting?.attendance.includes(memberId)??false}
  toggleAttendance(groupId:string,memberId:string){const next=structuredClone(this.state());const g=next.groups.find(x=>x.id===groupId);const meeting=g?.meetings[g.meetings.length-1];if(!meeting)return;meeting.attendance=meeting.attendance.includes(memberId)?meeting.attendance.filter(id=>id!==memberId):[...meeting.attendance,memberId];this.persist(next)}
  claimAssignment(groupId:string,assignmentId:string){const next=structuredClone(this.state());const a=next.groups.find(g=>g.id===groupId)?.assignments.find(x=>x.id===assignmentId);if(a){a.owner='Jordan Davis';a.status='Assigned';this.persist(next)}}
  updatePlacement(id:string,status:string){const next=structuredClone(this.state());const p=next.placements.find(x=>x.id===id);if(p){p.status=status;this.persist(next)}}
  placeRequest(p:DwcPlacement){const next=structuredClone(this.state());const req=next.placements.find(x=>x.id===p.id);const g=next.groups.find(x=>x.name===p.suggestedGroup);if(req)req.status='Placed';if(g&&g.members.length<g.capacity&&!g.members.some(m=>m.name===p.name))g.members.push({id:`member-${Date.now()}`,name:p.name,role:'Member',joined:'Apr 2027',status:'Active',leadershipInterest:false,careStatus:'None'});this.persist(next)}
  requestJoin(g:DwcGroup){const next=structuredClone(this.state());next.placements.unshift({id:`request-${Date.now()}`,name:'Demo Website Visitor',interest:g.audience,preferredDay:g.day,area:g.area,suggestedGroup:g.name,status:g.members.length>=g.capacity?'Waitlist':'New',note:'Submitted from the public Find a DEG experience.'});this.persist(next);this.section.set('placements')}
  rolloverSemester(){const next=structuredClone(this.state());const summer=next.semesters.find(s=>s.id==='summer-2027');if(summer)summer.status='Ready for leader confirmation';this.persist(next)}
}
