import { CommonModule } from '@angular/common';
import { Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DwcFormationStateService, FormationGroup } from '../core/dwc-formation-state.service';
import { DivineGroupDiscoveryProfile, DwcGroupsExperienceService } from '../core/dwc-groups-experience.service';

interface GroupCard {
  group: FormationGroup;
  profile: DivineGroupDiscoveryProfile;
  openSeats: number;
  day: string;
  status: 'Open' | 'Nearly full' | 'Waitlist';
}

@Component({
  selector: 'app-dwc-groups-hub',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <main class="groups-hub">
      @if (toast()) { <div class="toast" role="status"><strong>{{ toast() }}</strong><button type="button" (click)="toast.set('')">×</button></div> }

      <section class="groups-hero">
        <div class="hero-copy">
          <p class="eyebrow">Divine World Changers International Ministries</p>
          <h1>Find your people.<br><em>Grow on purpose.</em></h1>
          <p class="hero-lead">Divine Empowerment Groups are where relationships become discipleship—Scripture, prayer, honest conversation, practical obedience and a clear next step, together.</p>
          <div class="hero-actions"><button type="button" class="primary" (click)="directory.scrollIntoView({behavior:'smooth'})">Find a group</button><button type="button" class="text-link" (click)="leaderDialog.showModal()">Lead a group →</button></div>
        </div>
        <aside class="hero-semester"><span>Current semester</span><strong>Spring 2027</strong><p>February 7 – April 30</p><div><b>{{ cards().length }} featured groups</b><b>{{ totalOpenSeats() }} open seats</b></div><small>Groups move in seasons so people can connect, grow, rest and discern their next step.</small></aside>
      </section>

      <section class="pathway">
        <button type="button" class="path-card" (click)="directory.scrollIntoView({behavior:'smooth'})"><span>01</span><div><strong>Find a Group</strong><p>Search by life stage, day, area, childcare and availability.</p></div><b>Explore →</b></button>
        <a class="path-card" [href]="myGroupHref()"><span>02</span><div><strong>My Group</strong><p>Your gathering, formation pathway, prayer responses and journey.</p></div><b>Open →</b></a>
        <a class="path-card" [href]="leaderHref()"><span>03</span><div><strong>Leader Toolbox</strong><p>Prepare, shepherd people, communicate, develop leaders and multiply.</p></div><b>Lead →</b></a>
      </section>

      <section #directory class="directory-section">
        <header class="section-heading"><div><p class="eyebrow">Spring semester directory</p><h2>There is room for you here.</h2><p>Start with the people and rhythm that fit your season. The formation happens once you are connected.</p></div><button type="button" class="help-link" (click)="finderDialog.showModal()">Not sure? Help me find a group →</button></header>

        <div class="finder-bar">
          <label class="search-field"><span>Search</span><input [(ngModel)]="search" placeholder="Young adults, prayer, family..." /></label>
          <label><span>Group type</span><select [(ngModel)]="typeFilter"><option value="">All types</option>@for (type of groupTypes; track type) { <option [value]="type">{{ type }}</option> }</select></label>
          <label><span>Day</span><select [(ngModel)]="dayFilter"><option value="">Any day</option>@for (day of days; track day) { <option [value]="day">{{ day }}</option> }</select></label>
          <label><span>Area</span><select [(ngModel)]="locationFilter"><option value="">Any area</option><option>West</option><option>Central</option><option>East</option><option>South</option></select></label>
          <label class="check-filter"><input type="checkbox" [(ngModel)]="childcareOnly" /><span>Childcare</span></label>
          <label class="check-filter"><input type="checkbox" [(ngModel)]="openOnly" /><span>Open spots</span></label>
        </div>
        <div class="result-line"><strong>{{ filteredCards().length }} groups</strong><span>{{ activeFilterCopy() }}</span><button type="button" (click)="clearFilters()">Clear filters</button></div>

        <div class="group-grid">
          @for (card of filteredCards(); track card.group.id) {
            <article class="group-card" [attr.data-status]="card.status">
              <div class="group-art" [attr.data-group]="card.group.id"><span>{{ card.profile.type }}</span><b>{{ card.profile.lifeStage }}</b></div>
              <div class="group-content">
                <div class="group-status"><span>{{ card.status }}</span><small>{{ card.openSeats > 0 ? card.openSeats + ' spots available' : 'Join the waitlist' }}</small></div>
                <h3>{{ card.group.name }}</h3><p>{{ card.profile.description }}</p>
                <dl><div><dt>Leader</dt><dd>{{ card.group.leader }}</dd></div><div><dt>Meets</dt><dd>{{ card.group.meeting }}</dd></div><div><dt>Area</dt><dd>{{ card.profile.neighborhood }}</dd></div><div><dt>Format</dt><dd>{{ card.profile.meetingMode }}{{ card.group.childcare ? ' · Childcare' : '' }}</dd></div></dl>
                <div class="tags">@for (tag of card.profile.tags; track tag) { <span>{{ tag }}</span> }</div>
                <footer><button type="button" class="join-button" (click)="openJoin(card, joinDialog)">{{ card.status === 'Waitlist' ? 'Join waitlist' : 'Request to join' }}</button><a [href]="memberPreviewHref(card.group.id)">Preview group →</a></footer>
              </div>
            </article>
          } @empty {
            <article class="empty-state"><h3>No exact match yet.</h3><p>Send your preferences to the Groups Team instead of getting stuck.</p><button type="button" (click)="finderDialog.showModal()">Help me find a group</button></article>
          }
        </div>
      </section>

      <section class="my-group-strip"><div><p class="eyebrow">Your group</p><h2>{{ myGroup().name }}</h2><p>{{ myGroup().leader }} · {{ myGroup().meeting }} · {{ myGroup().location }}</p></div><div class="my-group-next"><span>Next formation gathering</span><strong>Week {{ state.currentSession().week }} · {{ state.currentSession().title }}</strong><small>{{ state.currentSession().scripture }}</small></div><div class="strip-actions"><a class="primary-link" [href]="myGroupHref()">Open My Group</a><a [href]="leaderHref()">Leader view →</a></div></section>

      <section class="leader-section">
        <header class="section-heading"><div><p class="eyebrow">Leader Toolbox</p><h2>Lead people, not paperwork.</h2><p>Roster, gatherings, formation, communication and leadership development stay connected to the same group.</p></div><a class="leader-home-link" [href]="leaderHref()">Open full leader dashboard →</a></header>
        <div class="tool-grid">
          <a [href]="leaderHref()"><span>THIS WEEK</span><strong>Prepare the gathering</strong><p>Scripture, questions, prayer, practice and the current formation track.</p><b>Week {{ state.currentSession().week }} →</b></a>
          <a [href]="toolsHref('people')"><span>PEOPLE</span><strong>Roster & follow-up</strong><p>Attendance, absences, prayer needs and next steps.</p><b>{{ state.followupCount() }} need follow-up →</b></a>
          <a [href]="toolsHref('curriculum')"><span>FORMATION</span><strong>Curriculum & resources</strong><p>DWCIM tracks and Kingdom Academy resources connected to this group.</p><b>{{ state.selectedTrack().title }} →</b></a>
          <a [href]="toolsHref('leaders')"><span>LEADERSHIP</span><strong>Develop the next leader</strong><p>Apprentice, co-lead, multiply and strengthen clusters.</p><b>{{ state.emergingLeaders().length }} emerging →</b></a>
          <a [href]="toolsHref('semester')"><span>SEMESTER</span><strong>Review & multiply</strong><p>Capture testimonies, next steps, commissioning and rollover decisions.</p><b>Close the loop →</b></a>
          <button type="button" class="tool-button" (click)="communicationDialog.showModal()"><span>COMMUNICATION</span><strong>Message your group</strong><p>Send one update to the People-backed roster.</p><b>Compose →</b></button>
        </div>
      </section>

      <section class="oversight-grid">
        <article class="oversight-panel"><header><div><p class="eyebrow">Groups Team</p><h2>What needs attention</h2></div><a href="/organization/dwc/admin">Open admin workspace →</a></header><div class="attention-row"><span>{{ experience.pendingJoinCount() }}</span><div><strong>join request awaiting leader review</strong><p>Nia Robinson · Young Adults DEG</p></div></div><div class="attention-row"><span>{{ experience.placementCount() }}</span><div><strong>person needs placement help</strong><p>Match preferences against capacity, area and group type.</p></div></div><div class="attention-row"><span>{{ experience.leaderPipelineCount() }}</span><div><strong>leader in development</strong><p>Derrick Lewis · training toward a men’s prayer group.</p></div></div></article>
        <article class="semester-panel"><p class="eyebrow">Healthy rhythm</p><h2>Groups move in seasons.</h2><div class="semester-row"><span>Fall 2026</span><b>Completed</b><small>16 groups · 197 people</small></div><div class="semester-row current"><span>Spring 2027</span><b>Current</b><small>Formation, care and leadership development in progress</small></div><div class="semester-row"><span>Summer 2027</span><b>Planning</b><small>Continue, pause, change track or multiply</small></div></article>
      </section>

      <section class="lead-cta"><div><p class="eyebrow">Multiplication</p><h2>You do not need to know everything to lead people.</h2><p>A willing heart, healthy accountability, leader training and a clear formation pathway are enough to begin.</p></div><ol><li><span>1</span>Express interest</li><li><span>2</span>Complete leader training</li><li><span>3</span>Meet with Groups leadership</li><li><span>4</span>Build your group</li><li><span>5</span>Launch with support</li></ol><button type="button" (click)="leaderDialog.showModal()">Start the leadership path</button></section>

      <dialog #joinDialog class="form-dialog"><form (submit)="$event.preventDefault(); saveJoin(joinDialog)"><header><div><p class="eyebrow">Connect with a Divine Group</p><h2>{{ selectedCard()?.group?.name }}</h2><p>{{ selectedCard()?.group?.leader }} · {{ selectedCard()?.group?.meeting }}</p></div><button type="button" class="close" (click)="joinDialog.close()">×</button></header><div class="form-body"><label>Your name<input [(ngModel)]="joinDraft.name" name="joinName" required /></label><label>Email<input [(ngModel)]="joinDraft.email" name="joinEmail" type="email" required /></label><label>Phone<input [(ngModel)]="joinDraft.phone" name="joinPhone" /></label><label class="wide">Anything the leader should know?<textarea [(ngModel)]="joinDraft.note" name="joinNote" rows="4"></textarea></label></div><footer><button type="button" class="secondary" (click)="joinDialog.close()">Cancel</button><button type="submit" class="primary">{{ selectedCard()?.status === 'Waitlist' ? 'Join waitlist' : 'Send request' }}</button></footer></form></dialog>

      <dialog #finderDialog class="form-dialog"><form (submit)="$event.preventDefault(); saveFinder(finderDialog)"><header><div><p class="eyebrow">Placement help</p><h2>Help me find a group</h2><p>Tell the Groups Team what would make connection sustainable for you.</p></div><button type="button" class="close" (click)="finderDialog.close()">×</button></header><div class="form-body"><label>Your name<input [(ngModel)]="finderDraft.name" name="finderName" required /></label><label>Email<input [(ngModel)]="finderDraft.email" name="finderEmail" type="email" required /></label><label>Preferred day<select [(ngModel)]="finderDraft.dayPreference" name="finderDay"><option value="">Flexible</option>@for (day of days; track day) { <option [value]="day">{{ day }}</option> }</select></label><label>Preferred area<select [(ngModel)]="finderDraft.areaPreference" name="finderArea"><option value="">Flexible</option><option>West</option><option>Central</option><option>East</option><option>South</option></select></label><label>Group preference<select [(ngModel)]="finderDraft.groupPreference" name="finderType"><option value="">Open to suggestions</option>@for (type of groupTypes; track type) { <option [value]="type">{{ type }}</option> }</select></label><label class="checkbox"><input type="checkbox" [(ngModel)]="finderDraft.childcareNeeded" name="finderChildcare" /> Childcare matters for my placement</label><label class="wide">Anything else?<textarea [(ngModel)]="finderDraft.note" name="finderNote" rows="4"></textarea></label></div><footer><button type="button" class="secondary" (click)="finderDialog.close()">Cancel</button><button type="submit" class="primary">Send to Groups Team</button></footer></form></dialog>

      <dialog #leaderDialog class="form-dialog"><form (submit)="$event.preventDefault(); saveLeader(leaderDialog)"><header><div><p class="eyebrow">Leadership pathway</p><h2>Lead a Divine Empowerment Group</h2><p>Interest starts a conversation—it does not automatically publish a group.</p></div><button type="button" class="close" (click)="leaderDialog.close()">×</button></header><div class="form-body"><label>Your name<input [(ngModel)]="leaderDraft.name" name="leaderName" required /></label><label>Email<input [(ngModel)]="leaderDraft.email" name="leaderEmail" type="email" required /></label><label class="wide">What kind of group is on your heart?<input [(ngModel)]="leaderDraft.groupIdea" name="leaderIdea" /></label><label>Availability<input [(ngModel)]="leaderDraft.availability" name="leaderAvailability" /></label><label class="wide">Current serving / leadership experience<textarea [(ngModel)]="leaderDraft.experience" name="leaderExperience" rows="4"></textarea></label></div><footer><button type="button" class="secondary" (click)="leaderDialog.close()">Cancel</button><button type="submit" class="primary">Express interest</button></footer></form></dialog>

      <dialog #communicationDialog class="form-dialog"><form (submit)="$event.preventDefault(); sendCommunication(communicationDialog)"><header><div><p class="eyebrow">Group communication</p><h2>Message {{ myGroup().name }}</h2><p>One message to the People-backed roster.</p></div><button type="button" class="close" (click)="communicationDialog.close()">×</button></header><div class="form-body"><label>Audience<select [(ngModel)]="messageDraft.audience" name="messageAudience"><option>Entire group</option><option>Leaders only</option><option>Members needing follow-up</option></select></label><label class="wide">Message<textarea [(ngModel)]="messageDraft.body" name="messageBody" rows="5" required></textarea></label></div><footer><button type="button" class="secondary" (click)="communicationDialog.close()">Cancel</button><button type="submit" class="primary">Send demo message</button></footer></form></dialog>
    </main>
  `,
  styles: [`
    :host{display:block}.groups-hub{--ink:#2d2928;--muted:#756d69;--line:rgba(67,50,47,.13);--paper:#fffdf8;--plum:#6f4a73;--plum-dark:#4e3352;max-width:1440px;margin:0 auto;padding:22px 28px 72px;color:var(--ink)}.eyebrow{margin:0;color:var(--plum);font-size:.61rem;font-weight:900;letter-spacing:.115em;text-transform:uppercase}.groups-hero{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(300px,.6fr);gap:32px;min-height:390px;padding:46px 48px;border-radius:26px;background:linear-gradient(125deg,#fffdf8,#faf2e7 58%,#eee0e8);box-shadow:inset 0 0 0 1px var(--line)}.hero-copy{align-self:center}.hero-copy h1{margin:12px 0 18px;font-family:Georgia,'Times New Roman',serif;font-size:clamp(3rem,6vw,5.5rem);font-weight:500;line-height:.9;letter-spacing:-.055em}.hero-copy h1 em{color:var(--plum);font-style:normal}.hero-lead{max-width:760px;margin:0;color:#665f5b;font-size:.9rem;line-height:1.75}.hero-actions{display:flex;align-items:center;gap:18px;margin-top:26px}.primary,.primary-link{display:inline-flex;min-height:44px;align-items:center;justify-content:center;padding:0 17px;border:0;border-radius:9px;background:var(--plum-dark);color:#fff;font:inherit;font-size:.68rem;font-weight:850;text-decoration:none;cursor:pointer}.text-link,.help-link{border:0;background:transparent;color:var(--plum);font:inherit;font-size:.68rem;font-weight:850;cursor:pointer}.hero-semester{display:grid;align-content:center;padding:28px;border-left:1px solid rgba(95,67,75,.16);background:rgba(255,255,255,.42)}.hero-semester>span{color:#8c7872;font-size:.6rem;font-weight:850;text-transform:uppercase}.hero-semester>strong{margin:8px 0 3px;font-family:Georgia,'Times New Roman',serif;font-size:2.1rem;font-weight:500}.hero-semester>p{margin:0;color:var(--muted);font-size:.7rem}.hero-semester>div{display:flex;flex-wrap:wrap;gap:7px;margin:20px 0 14px}.hero-semester b{padding:7px 9px;border-radius:999px;background:#fff;font-size:.6rem}.hero-semester small{color:#80746f;font-size:.62rem;line-height:1.55}
    .pathway{display:grid;grid-template-columns:repeat(3,1fr);margin:18px 0 44px;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.path-card{display:grid;grid-template-columns:auto 1fr auto;gap:14px;align-items:center;min-height:98px;padding:16px 20px;border:0;border-right:1px solid var(--line);background:transparent;color:inherit;text-align:left;text-decoration:none;cursor:pointer;font:inherit}.path-card:last-child{border-right:0}.path-card:hover{background:#faf5ed}.path-card>span{display:grid;width:32px;height:32px;place-items:center;border-radius:50%;background:#efe6df;color:var(--plum);font-size:.61rem;font-weight:900}.path-card strong{display:block;font-family:Georgia,'Times New Roman',serif;font-size:1rem;font-weight:500}.path-card p{margin:4px 0 0;color:var(--muted);font-size:.61rem;line-height:1.45}.path-card>b{color:var(--plum);font-size:.62rem}.section-heading{display:flex;justify-content:space-between;gap:26px;align-items:end;margin-bottom:18px}.section-heading h2{margin:6px 0 7px;font-family:Georgia,'Times New Roman',serif;font-size:2.2rem;font-weight:500;letter-spacing:-.035em}.section-heading p:not(.eyebrow){max-width:720px;margin:0;color:var(--muted);font-size:.73rem;line-height:1.6}.finder-bar{display:grid;grid-template-columns:minmax(220px,1.4fr) repeat(3,minmax(125px,.7fr)) auto auto;gap:9px;align-items:end;padding:13px;border:1px solid var(--line);border-radius:14px;background:#fff}.finder-bar label{display:grid;gap:5px}.finder-bar label>span{color:#887e79;font-size:.55rem;font-weight:800;text-transform:uppercase}.finder-bar input,.finder-bar select{min-height:42px;box-sizing:border-box;width:100%;padding:0 10px;border:1px solid #ddd7d1;border-radius:8px;background:#fffdfa;color:var(--ink);font:inherit;font-size:.69rem}.check-filter{display:flex!important;align-items:center;gap:7px;min-height:42px;padding:0 9px;border:1px solid #e2ddd7;border-radius:8px}.check-filter input{width:auto!important;min-height:auto!important}.check-filter span{white-space:nowrap;text-transform:none!important}.result-line{display:flex;align-items:center;gap:10px;padding:12px 2px;color:#837873;font-size:.62rem}.result-line button{margin-left:auto;border:0;background:transparent;color:var(--plum);font:inherit;font-size:.61rem;font-weight:800;cursor:pointer}
    .group-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.group-card{display:grid;grid-template-columns:170px minmax(0,1fr);min-height:300px;border:1px solid var(--line);border-radius:18px;background:var(--paper);overflow:hidden}.group-art{display:grid;align-content:end;gap:4px;padding:19px;background:linear-gradient(155deg,#79587a,#49344d);color:#fff}.group-art[data-group='marriage-family']{background:linear-gradient(155deg,#a78368,#6f594b)}.group-art[data-group='men-of-valor']{background:linear-gradient(155deg,#5f6e70,#344245)}.group-art[data-group='women-purpose']{background:linear-gradient(155deg,#a47186,#684658)}.group-art span{font-size:.57rem;font-weight:850;text-transform:uppercase}.group-art b{font-family:Georgia,'Times New Roman',serif;font-size:1.12rem;font-weight:500}.group-content{padding:19px}.group-status{display:flex;justify-content:space-between;gap:12px}.group-status span{padding:5px 7px;border-radius:999px;background:#e9f3eb;color:#37694a;font-size:.55rem;font-weight:850}.group-card[data-status='Nearly full'] .group-status span{background:#fff2dd;color:#835d1b}.group-card[data-status='Waitlist'] .group-status span{background:#f1e9e6;color:#7c5f55}.group-status small{color:#938782;font-size:.56rem}.group-content h3{margin:11px 0 7px;font-family:Georgia,'Times New Roman',serif;font-size:1.38rem;font-weight:500}.group-content>p{margin:0;color:var(--muted);font-size:.66rem;line-height:1.55}.group-content dl{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:14px 0}.group-content dt{color:#968b86;font-size:.52rem;text-transform:uppercase}.group-content dd{margin:2px 0 0;font-size:.61rem;font-weight:750}.tags{display:flex;flex-wrap:wrap;gap:5px}.tags span{padding:5px 7px;border-radius:999px;background:#f4eee8;color:#6c5d57;font-size:.54rem}.group-content footer{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:17px}.join-button{min-height:39px;padding:0 12px;border:0;border-radius:8px;background:var(--plum-dark);color:#fff;font-size:.61rem;font-weight:850;cursor:pointer}.group-content footer a{color:var(--plum);font-size:.6rem;font-weight:800;text-decoration:none}.empty-state{grid-column:1/-1;padding:36px;border:1px dashed #d7cec8;border-radius:16px;text-align:center}.empty-state h3{font-family:Georgia,'Times New Roman',serif;font-size:1.45rem;font-weight:500}.empty-state p{color:var(--muted);font-size:.7rem}.empty-state button{border:0;background:transparent;color:var(--plum);font-weight:850;cursor:pointer}
    .my-group-strip{display:grid;grid-template-columns:1fr 1fr auto;gap:22px;align-items:center;margin:44px 0 20px;padding:23px 25px;border-radius:18px;background:#332e2d;color:#fff}.my-group-strip h2{margin:5px 0;font-family:Georgia,'Times New Roman',serif;font-size:1.6rem;font-weight:500}.my-group-strip p{margin:0;color:#d0c6c2;font-size:.63rem}.my-group-strip .eyebrow{color:#d7b895}.my-group-next{display:grid;gap:3px;padding-left:20px;border-left:1px solid rgba(255,255,255,.15)}.my-group-next span,.my-group-next small{color:#cfc5c1;font-size:.56rem}.my-group-next strong{font-size:.7rem}.strip-actions{display:flex;align-items:center;gap:11px}.strip-actions>a:last-child{color:#e3d7d0;font-size:.6rem;text-decoration:none}.leader-section{padding:32px 0}.leader-home-link,.oversight-panel header a{color:var(--plum);font-size:.62rem;font-weight:850;text-decoration:none}.tool-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.tool-grid>a,.tool-button{display:grid;min-height:160px;box-sizing:border-box;padding:18px;border:1px solid var(--line);border-radius:14px;background:#fffdf9;color:inherit;text-align:left;text-decoration:none;cursor:pointer;font:inherit}.tool-grid>a:hover,.tool-button:hover{background:#faf4eb}.tool-grid span{color:var(--plum);font-size:.54rem;font-weight:900;letter-spacing:.08em}.tool-grid strong{margin:8px 0 6px;font-family:Georgia,'Times New Roman',serif;font-size:1.06rem;font-weight:500}.tool-grid p{margin:0;color:var(--muted);font-size:.62rem;line-height:1.5}.tool-grid b{align-self:end;margin-top:13px;color:var(--plum);font-size:.59rem}
    .oversight-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px;margin:18px 0 40px}.oversight-panel,.semester-panel{padding:23px;border:1px solid var(--line);border-radius:18px;background:#fffdf9}.oversight-panel header{display:flex;justify-content:space-between;gap:18px}.oversight-panel h2,.semester-panel h2{margin:5px 0 12px;font-family:Georgia,'Times New Roman',serif;font-size:1.45rem;font-weight:500}.attention-row{display:grid;grid-template-columns:38px 1fr;gap:12px;padding:12px 0;border-top:1px solid var(--line)}.attention-row>span{display:grid;width:34px;height:34px;place-items:center;border-radius:10px;background:#f1e8f0;color:var(--plum);font-weight:850}.attention-row strong{font-size:.66rem}.attention-row p{margin:3px 0 0;color:var(--muted);font-size:.6rem}.semester-row{display:grid;grid-template-columns:105px auto 1fr;gap:11px;align-items:center;padding:11px 0;border-top:1px solid var(--line)}.semester-row span{font-size:.66rem;font-weight:800}.semester-row b{padding:5px 7px;border-radius:999px;background:#eee8e3;color:#725f55;font-size:.53rem}.semester-row.current b{background:#e9f3eb;color:#37694a}.semester-row small{color:var(--muted);font-size:.57rem}.lead-cta{display:grid;grid-template-columns:1.1fr 1fr auto;gap:26px;align-items:center;padding:30px;border-radius:22px;background:linear-gradient(125deg,#f4e8ef,#f7eee3)}.lead-cta h2{margin:5px 0 8px;font-family:Georgia,'Times New Roman',serif;font-size:1.65rem;font-weight:500}.lead-cta p:not(.eyebrow){margin:0;color:var(--muted);font-size:.67rem;line-height:1.55}.lead-cta ol{display:grid;gap:7px;margin:0;padding:0;list-style:none}.lead-cta li{display:flex;align-items:center;gap:8px;font-size:.61rem;font-weight:750}.lead-cta li span{display:grid;width:22px;height:22px;place-items:center;border-radius:50%;background:#fff;color:var(--plum);font-size:.54rem}.lead-cta>button{min-height:43px;padding:0 14px;border:0;border-radius:9px;background:var(--plum-dark);color:#fff;font:inherit;font-size:.62rem;font-weight:850;cursor:pointer;white-space:nowrap}
    .form-dialog{width:min(700px,calc(100vw - 28px));max-width:none;padding:0;border:0;border-radius:18px;background:#fffdf9;box-shadow:0 30px 100px rgba(20,14,19,.3)}.form-dialog::backdrop{background:rgba(21,15,20,.45);backdrop-filter:blur(3px)}.form-dialog form>header{display:flex;justify-content:space-between;gap:20px;padding:22px 24px;border-bottom:1px solid var(--line)}.form-dialog h2{margin:5px 0;font-family:Georgia,'Times New Roman',serif;font-size:1.5rem;font-weight:500}.form-dialog header p:last-child{margin:0;color:var(--muted);font-size:.65rem}.close{width:36px;height:36px;border:0;border-radius:50%;background:#f1ece8;color:#5f5652;font-size:1.1rem;cursor:pointer}.form-body{display:grid;grid-template-columns:1fr 1fr;gap:13px;padding:22px 24px}.form-body label{display:grid;gap:6px;color:#615955;font-size:.62rem;font-weight:800}.form-body .wide{grid-column:1/-1}.form-body input,.form-body select,.form-body textarea{box-sizing:border-box;width:100%;padding:10px;border:1px solid #d9d2cc;border-radius:8px;background:#fff;color:var(--ink);font:inherit}.form-body .checkbox{display:flex;align-items:center;gap:8px}.form-body .checkbox input{width:auto}.form-dialog footer{display:flex;justify-content:flex-end;gap:8px;padding:15px 24px;border-top:1px solid var(--line)}.form-dialog footer button{min-height:40px;padding:0 14px;border-radius:8px;font:inherit;font-size:.64rem;font-weight:850;cursor:pointer}.form-dialog .secondary{border:1px solid #ddd5cf;background:#fff;color:#5e5651}.form-dialog .primary{border:0;background:var(--plum-dark);color:#fff}.toast{position:fixed;top:78px;right:24px;z-index:100;display:flex;align-items:center;gap:16px;max-width:420px;padding:13px 15px;border:1px solid #d9dfd8;border-radius:10px;background:#fffdf9;box-shadow:0 18px 50px rgba(24,17,22,.14)}.toast strong{font-size:.69rem}.toast button{border:0;background:transparent;color:#756a64;font-size:1rem;cursor:pointer}
    @media(max-width:1050px){.groups-hero{grid-template-columns:1fr}.hero-semester{border-left:0;border-top:1px solid rgba(95,67,75,.16)}.finder-bar{grid-template-columns:1fr 1fr 1fr}.group-grid{grid-template-columns:1fr}.tool-grid{grid-template-columns:1fr 1fr}.lead-cta{grid-template-columns:1fr 1fr}.lead-cta>button{grid-column:1/-1;justify-self:start}.my-group-strip{grid-template-columns:1fr 1fr}.strip-actions{grid-column:1/-1}}
    @media(max-width:720px){.groups-hub{padding:14px 12px 50px}.groups-hero{padding:28px 20px}.pathway,.oversight-grid,.tool-grid{grid-template-columns:1fr}.path-card{border-right:0;border-bottom:1px solid var(--line)}.section-heading{align-items:flex-start;flex-direction:column}.finder-bar{grid-template-columns:1fr}.group-card{grid-template-columns:1fr}.group-art{min-height:115px}.my-group-strip{grid-template-columns:1fr}.my-group-next{padding-left:0;border-left:0;border-top:1px solid rgba(255,255,255,.15);padding-top:14px}.lead-cta{grid-template-columns:1fr}.form-body{grid-template-columns:1fr}.form-body .wide{grid-column:auto}.semester-row{grid-template-columns:1fr}.hero-actions{align-items:flex-start;flex-direction:column}}
  `],
})
export class DwcGroupsHubComponent {
  readonly groupTypes = ['Young Adults', 'Marriage & Family', 'Men', 'Women'];
  readonly days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  search = '';
  typeFilter = '';
  dayFilter = '';
  locationFilter = '';
  childcareOnly = false;
  openOnly = false;
  readonly selectedCard = signal<GroupCard | null>(null);
  readonly toast = signal('');

  joinDraft = { name: 'Michael Davis', email: 'michael@example.com', phone: '', note: '' };
  finderDraft = { name: 'Michael Davis', email: 'michael@example.com', dayPreference: '', areaPreference: '', groupPreference: '', childcareNeeded: false, note: '' };
  leaderDraft = { name: 'Michael Davis', email: 'michael@example.com', groupIdea: '', availability: '', experience: '' };
  messageDraft = { audience: 'Entire group', body: '' };

  readonly cards = computed<GroupCard[]>(() => this.state.groups().map(group => {
    const profile = this.experience.profileFor(group.id) ?? {
      groupId: group.id, type: 'Formation' as const, lifeStage: 'All adults', description: 'A Divine Empowerment Group growing through Scripture, prayer and relational formation.', capacity: Math.max(group.members + 3, 12), meetingMode: 'In person' as const, joinPolicy: 'Request to join' as const, acceptingMembers: true, neighborhood: group.location, tags: ['Formation'],
    };
    const openSeats = Math.max(profile.capacity - group.members, 0);
    const status: GroupCard['status'] = !profile.acceptingMembers || openSeats === 0 ? 'Waitlist' : openSeats <= 2 ? 'Nearly full' : 'Open';
    return { group, profile, openSeats, day: group.meeting.split('·')[0].trim(), status };
  }));
  readonly totalOpenSeats = computed(() => this.cards().reduce((total, card) => total + card.openSeats, 0));
  readonly myGroup = computed(() => this.state.groups().find(group => group.memberIds.includes(this.state.myMember().id)) ?? this.state.selectedGroup());

  constructor(readonly state: DwcFormationStateService, readonly experience: DwcGroupsExperienceService) {}

  filteredCards(): GroupCard[] {
    const query = this.search.trim().toLowerCase();
    return this.cards().filter(card => {
      const haystack = [card.group.name, card.group.leader, card.profile.type, card.profile.lifeStage, card.profile.description, card.profile.neighborhood, ...card.profile.tags].join(' ').toLowerCase();
      return (!query || haystack.includes(query))
        && (!this.typeFilter || card.profile.type === this.typeFilter)
        && (!this.dayFilter || card.day === this.dayFilter)
        && (!this.locationFilter || card.profile.neighborhood.toLowerCase().includes(this.locationFilter.toLowerCase()))
        && (!this.childcareOnly || card.group.childcare)
        && (!this.openOnly || card.status !== 'Waitlist');
    });
  }
  activeFilterCopy(): string { const parts = [this.typeFilter, this.dayFilter, this.locationFilter, this.childcareOnly ? 'childcare' : '', this.openOnly ? 'open spots' : ''].filter(Boolean); return parts.length ? parts.join(' · ') : 'Browse all current demo groups'; }
  clearFilters(): void { this.search = ''; this.typeFilter = ''; this.dayFilter = ''; this.locationFilter = ''; this.childcareOnly = false; this.openOnly = false; }
  openJoin(card: GroupCard, dialog: HTMLDialogElement): void { this.selectedCard.set(card); this.joinDraft.note = ''; dialog.showModal(); }
  saveJoin(dialog: HTMLDialogElement): void { const card = this.selectedCard(); if (!card) return; const result = this.experience.requestJoin({ groupId: card.group.id, ...this.joinDraft }); this.toast.set(result.status === 'Waitlisted' ? `You were added to the ${card.group.name} waitlist.` : `Your request was sent to ${card.group.leader}.`); dialog.close(); }
  saveFinder(dialog: HTMLDialogElement): void { this.experience.requestFinderHelp({ ...this.finderDraft }); this.toast.set('Your preferences were sent to the Divine Groups placement queue.'); dialog.close(); }
  saveLeader(dialog: HTMLDialogElement): void { this.experience.expressLeaderInterest({ ...this.leaderDraft }); this.toast.set('Leadership interest received. The next step is Divine Groups leader training.'); dialog.close(); }
  sendCommunication(dialog: HTMLDialogElement): void { if (!this.messageDraft.body.trim()) return; this.toast.set(`Demo message queued for ${this.messageDraft.audience.toLowerCase()}.`); this.messageDraft.body = ''; dialog.close(); }
  myGroupHref(): string { return `/organization/dwc/my-group?group=${encodeURIComponent(this.myGroup().id)}`; }
  memberPreviewHref(groupId: string): string { return `/organization/dwc/my-group?group=${encodeURIComponent(groupId)}`; }
  leaderHref(): string { return `/organization/dwc/formation?group=${encodeURIComponent(this.myGroup().id)}`; }
  toolsHref(tab: 'curriculum'|'people'|'leaders'|'semester'): string { return `/organization/dwc/formation/tools?group=${encodeURIComponent(this.myGroup().id)}&tab=${tab}`; }
}
