import { Component, Input, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ProductInfo } from '../core/models';

interface HkApplication { id:string; name:string; phone:string; email:string; referral:string; need:string; eventDate:string; availability:string; transportation:string; status:string; note:string; }
interface Measurement { date:string; jacket:string; sleeve:string; neck:string; shirtSleeve:string; waist:string; inseam:string; shoe:string; height:string; notes:string; }
interface RecipientTimeline { date:string; title:string; detail:string; }
interface HkRecipient { id:string; name:string; status:string; referral:string; need:string; nextAppointment:string; measurements:Measurement[]; outfitId:string|null; mentorshipId:string|null; timeline:RecipientTimeline[]; }
interface Appointment { id:string; recipientId:string; date:string; time:string; type:string; owner:string; status:string; notes:string; }
interface InventoryItem { id:string; category:string; size:string; color:string; condition:string; status:string; recipientId:string|null; source:string; }
interface OutfitItem { label:string; inventoryId:string|null; required:boolean; }
interface Outfit { id:string; recipientId:string; name:string; items:OutfitItem[]; status:string; alterationPartner:string; alterationStatus:string; }
interface Partner { id:string; name:string; type:string; contact:string; email:string; active:number; completed:number; turnaround:string; referrals:number; notes:string; }
interface Transaction { id:string; date:string; type:string; description:string; partner:string; recipient:string; value:string; }
interface Mentor { id:string; name:string; capacity:number; active:number; focus:string[]; }
interface MentorshipMeeting { id:string; date:string; duration:string; topics:string[]; note:string; privacy:string; followUps:string[]; }
interface MentorshipGoal { id:string; category:string; title:string; due:string; status:string; resource:string; }
interface Milestone { date:string; title:string; detail:string; }
interface Mentorship { id:string; menteeId:string; mentorId:string; program:string; status:string; started:string; cadence:string; focus:string[]; meetings:MentorshipMeeting[]; goals:MentorshipGoal[]; milestones:Milestone[]; }
interface Cohort { id:string; name:string; leader:string; season:string; members:string[]; topics:string[]; }
interface VolunteerAssignment { id:string; event:string; date:string; role:string; owner:string; status:string; }
interface HkState { applications:HkApplication[]; recipients:HkRecipient[]; appointments:Appointment[]; inventory:InventoryItem[]; outfits:Outfit[]; partners:Partner[]; transactions:Transaction[]; mentors:Mentor[]; mentorships:Mentorship[]; cohorts:Cohort[]; volunteers:VolunteerAssignment[]; }

const NAMES=['Marcus Johnson','James Carter','Andre Lewis','DeShawn Reed','Caleb Moore','Tyler Brown','Isaiah Green','Malik Hill'];
const SEED:HkState={
  applications:[
    {id:'app1',name:'Marcus Johnson',phone:'804-555-0141',email:'marcus.j@example.org',referral:'Richmond Workforce Center',need:'Interview attire for a second-round interview',eventDate:'Sep 18, 2026',availability:'Weekday afternoons',transportation:'Has transportation',status:'Approved',note:'Interview with a regional logistics employer.'},
    {id:'app2',name:'DeShawn Reed',phone:'804-555-0198',email:'deshawn@example.org',referral:'Community partner',need:'Suit for employment interview and church leadership event',eventDate:'Sep 24, 2026',availability:'Tuesday / Thursday',transportation:'Needs ride coordination',status:'Under Review',note:'Verify preferred appointment date.'},
    {id:'app3',name:'Caleb Moore',phone:'804-555-0165',email:'caleb@example.org',referral:'Self referral',need:'Professional clothing for new job',eventDate:'Oct 1, 2026',availability:'Saturday mornings',transportation:'Has transportation',status:'New',note:'First-time request.'},
    {id:'app4',name:'Isaiah Green',phone:'804-555-0112',email:'isaiah@example.org',referral:'Youth development partner',need:'Interview attire and mentorship interest',eventDate:'Sep 28, 2026',availability:'After 4 PM',transportation:'Needs ride coordination',status:'Need More Information',note:'Need shoe size and referral contact.'},
    {id:'app5',name:'Malik Hill',phone:'804-555-0127',email:'malik@example.org',referral:'Church partner',need:'Career fair attire',eventDate:'Oct 5, 2026',availability:'Monday evening',transportation:'Has transportation',status:'Waitlisted',note:'Awaiting inventory in jacket size.'}
  ],
  recipients:[
    {id:'r1',name:'Marcus Johnson',status:'Active Recipient',referral:'Richmond Workforce Center',need:'Interview attire',nextAppointment:'Sep 14 · 2:00 PM · Alteration fitting',outfitId:'o1',mentorshipId:'ment1',measurements:[{date:'Sep 5, 2026',jacket:'44R',sleeve:'34',neck:'17',shirtSleeve:'34',waist:'36',inseam:'32',shoe:'11',height:'6 ft 0 in',notes:'Athletic shoulder; prefers classic fit.'},{date:'Mar 8, 2026',jacket:'42R',sleeve:'34',neck:'16.5',shirtSleeve:'34',waist:'34',inseam:'32',shoe:'11',height:'6 ft 0 in',notes:'Prior measurement set retained for history.'}],timeline:[{date:'Sep 2',title:'Application submitted',detail:'Referred by Richmond Workforce Center.'},{date:'Sep 3',title:'Approved',detail:'Approved by Alicia Brown.'},{date:'Sep 5',title:'Measurements confirmed',detail:'Professional fitting profile updated.'},{date:'Sep 5',title:'Navy interview outfit assigned',detail:'Five required pieces reserved.'},{date:'Sep 7',title:'Mentorship matched',detail:'Pastor Hickman accepted the mentorship relationship.'}]},
    {id:'r2',name:'James Carter',status:'Active Recipient',referral:'Community partner',need:'New employment wardrobe',nextAppointment:'Sep 16 · 11:30 AM · Pickup',outfitId:'o2',mentorshipId:'ment2',measurements:[{date:'Aug 25, 2026',jacket:'42L',sleeve:'36',neck:'16.5',shirtSleeve:'36',waist:'34',inseam:'34',shoe:'12',height:'6 ft 2 in',notes:'Long fit.'}],timeline:[{date:'Aug 21',title:'Approved',detail:'Application moved into service.'},{date:'Aug 25',title:'Fitting completed',detail:'Charcoal outfit assigned.'},{date:'Aug 29',title:'Mentorship started',detail:'Employment and spiritual-growth goals established.'}]},
    {id:'r3',name:'Andre Lewis',status:'Active Recipient',referral:'Workforce partner',need:'Interview attire',nextAppointment:'Sep 18 · 1:00 PM · Measurements',outfitId:null,mentorshipId:'ment3',measurements:[],timeline:[{date:'Sep 1',title:'Approved',detail:'Ready to schedule measurements.'},{date:'Sep 4',title:'Mentorship interest confirmed',detail:'Requested leadership and employment mentoring.'}]},
    {id:'r4',name:'Tyler Brown',status:'Completed',referral:'Church partner',need:'Interview attire',nextAppointment:'Follow-up Oct 1',outfitId:'o3',mentorshipId:null,measurements:[{date:'Jul 13, 2026',jacket:'40R',sleeve:'33',neck:'16',shirtSleeve:'33',waist:'32',inseam:'30',shoe:'10',height:'5 ft 9 in',notes:'Slim fit.'}],timeline:[{date:'Jul 13',title:'Fitting completed',detail:'Outfit assigned.'},{date:'Jul 20',title:'Outfit distributed',detail:'Service complete.'},{date:'Aug 14',title:'Employment milestone',detail:'Accepted new position.'}]}
  ],
  appointments:[
    {id:'apt1',recipientId:'r1',date:'Sep 14',time:'2:00 PM',type:'Alteration fitting',owner:'Jordan Davis',status:'Scheduled',notes:'Confirm trouser hem and jacket sleeve.'},
    {id:'apt2',recipientId:'r2',date:'Sep 16',time:'11:30 AM',type:'Pickup',owner:'Michael Davis',status:'Scheduled',notes:'Complete distribution transaction.'},
    {id:'apt3',recipientId:'r3',date:'Sep 18',time:'1:00 PM',type:'Measurements',owner:'Marcus Hill',status:'Scheduled',notes:'First fitting.'},
    {id:'apt4',recipientId:'r4',date:'Oct 1',time:'4:00 PM',type:'Follow-up',owner:'Alicia Brown',status:'Scheduled',notes:'Employment and ongoing-support follow-up.'}
  ],
  inventory:[
    {id:'i1',category:'Suit',size:'44R',color:'Navy',condition:'Excellent',status:'Assigned',recipientId:'r1',source:'Menswear donor'},
    {id:'i2',category:'Dress Shirt',size:'17 / 34',color:'White',condition:'New',status:'Assigned',recipientId:'r1',source:'Retail partner'},
    {id:'i3',category:'Tie',size:'One size',color:'Blue',condition:'Excellent',status:'Assigned',recipientId:'r1',source:'Community donor'},
    {id:'i4',category:'Belt',size:'36',color:'Black',condition:'Excellent',status:'Assigned',recipientId:'r1',source:'Retail partner'},
    {id:'i5',category:'Dress Shoes',size:'11',color:'Black',condition:'Good',status:'Assigned',recipientId:'r1',source:'Community donor'},
    {id:'i6',category:'Suit',size:'42L',color:'Charcoal',condition:'Excellent',status:'Reserved',recipientId:'r2',source:'Menswear donor'},
    {id:'i7',category:'Suit',size:'46R',color:'Navy',condition:'Excellent',status:'Available',recipientId:null,source:'Menswear donor'},
    {id:'i8',category:'Suit',size:'48R',color:'Charcoal',condition:'Good',status:'Available',recipientId:null,source:'Church partner'},
    {id:'i9',category:'Dress Shirt',size:'18 / 35',color:'White',condition:'New',status:'Available',recipientId:null,source:'Retail partner'},
    {id:'i10',category:'Dress Shoes',size:'13',color:'Black',condition:'Excellent',status:'Available',recipientId:null,source:'Community donor'},
    {id:'i11',category:'Suit',size:'40R',color:'Navy',condition:'Good',status:'Distributed',recipientId:'r4',source:'Menswear donor'},
    {id:'i12',category:'Dress Shoes',size:'10',color:'Brown',condition:'Fair',status:'Cleaning',recipientId:null,source:'Community donor'}
  ],
  outfits:[
    {id:'o1',recipientId:'r1',name:'Interview Outfit',status:'Alterations',alterationPartner:'Hickman Tailoring Partner',alterationStatus:'Sleeve and trouser hem · due Sep 13',items:[{label:'Navy Suit',inventoryId:'i1',required:true},{label:'White Shirt',inventoryId:'i2',required:true},{label:'Blue Tie',inventoryId:'i3',required:true},{label:'Black Belt',inventoryId:'i4',required:true},{label:'Black Shoes',inventoryId:'i5',required:true}]},
    {id:'o2',recipientId:'r2',name:'Employment Outfit',status:'Ready for Pickup',alterationPartner:'Hickman Tailoring Partner',alterationStatus:'Complete',items:[{label:'Charcoal Suit',inventoryId:'i6',required:true},{label:'White Shirt',inventoryId:null,required:true},{label:'Tie',inventoryId:null,required:true},{label:'Dress Shoes',inventoryId:null,required:true}]},
    {id:'o3',recipientId:'r4',name:'Interview Outfit',status:'Distributed',alterationPartner:'',alterationStatus:'None',items:[{label:'Navy Suit',inventoryId:'i11',required:true},{label:'White Shirt',inventoryId:null,required:true},{label:'Tie',inventoryId:null,required:true},{label:'Dress Shoes',inventoryId:null,required:true}]}
  ],
  partners:[
    {id:'partner1',name:'Hickman Tailoring Partner',type:'Alterations',contact:'James Smith',email:'james@tailoring.example',active:3,completed:17,turnaround:'4 days',referrals:0,notes:'Primary alteration partner.'},
    {id:'partner2',name:'Richmond Workforce Center',type:'Referral Partner',contact:'Danielle Green',email:'danielle@workforce.example',active:4,completed:18,turnaround:'—',referrals:23,notes:'Employment and interview referrals.'},
    {id:'partner3',name:'Menswear Community Partner',type:'Clothing Donor',contact:'Robert Jones',email:'robert@menswear.example',active:0,completed:142,turnaround:'Monthly',referrals:0,notes:'Suits and professional clothing donations.'},
    {id:'partner4',name:'New Hope Church',type:'Church Partner',contact:'Pastor Allen',email:'allen@newhope.example',active:2,completed:11,turnaround:'—',referrals:15,notes:'Referrals, volunteers, and follow-up support.'}
  ],
  transactions:[
    {id:'t1',date:'Sep 2',type:'Inventory receipt',description:'25 white dress shirts received',partner:'Menswear Community Partner',recipient:'—',value:'25 items'},
    {id:'t2',date:'Sep 5',type:'Service',description:'Alteration order opened',partner:'Hickman Tailoring Partner',recipient:'Marcus Johnson',value:'$28'},
    {id:'t3',date:'Aug 20',type:'Distribution',description:'Navy interview outfit distributed',partner:'—',recipient:'Tyler Brown',value:'5 pieces'}
  ],
  mentors:[
    {id:'mentor1',name:'Pastor Hickman',capacity:10,active:3,focus:['Character','Spiritual growth','Leadership','Employment']},
    {id:'mentor2',name:'Marcus Hill',capacity:6,active:1,focus:['Employment','Life skills','Discipline']},
    {id:'mentor3',name:'James Brown',capacity:5,active:2,focus:['Marriage','Leadership','Finances']}
  ],
  mentorships:[
    {id:'ment1',menteeId:'r1',mentorId:'mentor1',program:'Hey King Young Men Mentorship',status:'Active',started:'Sep 7, 2026',cadence:'Every other Thursday',focus:['Character','Employment','Spiritual growth','Leadership'],meetings:[{id:'mtg1',date:'Sep 7',duration:'45 min',topics:['Employment','Prayer','Personal goals'],note:'Established initial goals and prayer rhythm.',privacy:'Mentorship team',followUps:['Send résumé resource','Check in after interview','Meet again in two weeks']}],goals:[{id:'g1',category:'Employment',title:'Complete résumé',due:'Sep 12',status:'In Progress',resource:'Résumé Preparation'},{id:'g2',category:'Employment',title:'Attend second-round interview',due:'Sep 18',status:'Not Started',resource:'Interview Preparation'},{id:'g3',category:'Spiritual Development',title:'Establish a consistent prayer rhythm',due:'Oct 1',status:'In Progress',resource:'Prayer Guide'},{id:'g4',category:'Leadership',title:'Serve at one Hey King distribution day',due:'Oct 15',status:'Not Started',resource:'Volunteer Orientation'}],milestones:[{date:'Sep 5',title:'First suit fitting completed',detail:'Professional interview outfit prepared.'},{date:'Sep 7',title:'Mentorship began',detail:'Matched with Pastor Hickman.'}]},
    {id:'ment2',menteeId:'r2',mentorId:'mentor1',program:'Hey King Young Men Mentorship',status:'Active',started:'Aug 29, 2026',cadence:'Monthly + check-ins',focus:['Employment','Spiritual growth'],meetings:[{id:'mtg2',date:'Aug 29',duration:'60 min',topics:['Employment','Purpose'],note:'Discussed new job search and personal discipline.',privacy:'Private to mentor',followUps:['Review job list before next meeting']}],goals:[{id:'g5',category:'Employment',title:'Submit five applications',due:'Sep 20',status:'In Progress',resource:'Job Search Planner'},{id:'g6',category:'Spiritual Development',title:'Complete discipleship resource',due:'Oct 10',status:'Not Started',resource:'Identity & Purpose'}],milestones:[{date:'Aug 25',title:'Fitting completed',detail:'Charcoal employment outfit prepared.'}]},
    {id:'ment3',menteeId:'r3',mentorId:'mentor1',program:'Hey King Young Men Mentorship',status:'Active',started:'Sep 4, 2026',cadence:'Every other week',focus:['Leadership','Employment'],meetings:[],goals:[{id:'g7',category:'Leadership',title:'Identify one service opportunity',due:'Sep 30',status:'Not Started',resource:'Serving Guide'}],milestones:[{date:'Sep 4',title:'Mentorship interest confirmed',detail:'Pastor Hickman accepted the match.'}]}
  ],
  cohorts:[{id:'cohort1',name:'Hey King Brotherhood Cohort — Fall 2026',leader:'Pastor Hickman',season:'Fall 2026',members:['r1','r2','r3'],topics:['Identity','Discipline','Work','Marriage & relationships','Money','Prayer','Leadership','Purpose']}],
  volunteers:[
    {id:'v1',event:'Saturday Distribution Day',date:'Sep 19',role:'Intake',owner:'Alicia Brown',status:'Assigned'},
    {id:'v2',event:'Saturday Distribution Day',date:'Sep 19',role:'Measurements',owner:'Marcus Hill',status:'Assigned'},
    {id:'v3',event:'Saturday Distribution Day',date:'Sep 19',role:'Styling',owner:'Jordan Davis',status:'Assigned'},
    {id:'v4',event:'Saturday Distribution Day',date:'Sep 19',role:'Inventory',owner:'Michael Davis',status:'Assigned'},
    {id:'v5',event:'Saturday Distribution Day',date:'Sep 19',role:'Hospitality',owner:'',status:'Open'},
    {id:'v6',event:'Saturday Distribution Day',date:'Sep 19',role:'Photography',owner:'James Carter',status:'Assigned'}
  ]
};

@Component({
  selector:'app-heyy-king-space',
  standalone:true,
  imports:[FormsModule],
  template:`
  <section class="org-space" style="--org-accent:#8a6237;--org-soft:#f5efe6">
    <header class="org-hero"><div><p class="org-eyebrow">Hey King · Engagements + fulfillment</p><h1>Beyond the Suit</h1><p>Follow every young man from application to appointment, outfit, fulfillment, mentorship, milestones, and ongoing relationship—without losing the person behind the process.</p></div><div class="org-hero__actions"><button class="org-button org-button--outline" type="button" (click)="section.set('portal')">Recipient portal</button><button class="org-button org-button--primary" type="button" (click)="section.set('applications')">Open applications</button></div></header>
    <nav class="org-tabs" aria-label="Hey King operations">@for(tab of tabs;track tab.key){<button type="button" [class.active]="section()===tab.key" (click)="section.set(tab.key)">{{tab.label}}</button>}</nav>
    @switch(section()){
      @case('overview'){
        <div class="org-grid"><article class="org-surface org-pad org-span-12"><div class="org-metrics"><div class="org-metric"><span>Open applications</span><strong>{{openApplications()}}</strong><small>Need review or next step</small></div><div class="org-metric"><span>Appointments</span><strong>{{state().appointments.length}}</strong><small>Upcoming</small></div><div class="org-metric"><span>Outfits in process</span><strong>{{activeOutfits()}}</strong><small>Assigned / alterations</small></div><div class="org-metric"><span>Active mentorships</span><strong>{{activeMentorships()}}</strong><small>Young men in relationship</small></div><div class="org-metric"><span>Partners</span><strong>{{state().partners.length}}</strong><small>Referral + service network</small></div></div></article>
        <article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">Today's work</p><h2>Recipient command center</h2><p>The next human action is visible without turning people into ticket numbers.</p></div></header><div class="org-command-list"><div class="org-command"><span>01</span><div><strong>DeShawn Reed needs an application decision</strong><p>Interview need is Sep 24. Transportation coordination is also required.</p></div><button class="org-button" type="button" (click)="openApplication('app2')">Review</button></div><div class="org-command"><span>02</span><div><strong>Marcus Johnson alteration due before Sep 14</strong><p>Jacket sleeve and trouser hem are with the tailoring partner.</p></div><button class="org-button" type="button" (click)="section.set('outfits')">Track</button></div><div class="org-command"><span>03</span><div><strong>Hospitality assignment is open</strong><p>Saturday Distribution Day still needs one volunteer.</p></div><button class="org-button" type="button" (click)="section.set('volunteers')">Assign</button></div><div class="org-command"><span>04</span><div><strong>Pastor Hickman has three active mentees</strong><p>One interview follow-up and one résumé goal are due next.</p></div><button class="org-button" type="button" (click)="section.set('mentorship')">Mentorship</button></div></div></article>
        <aside class="org-surface org-pad org-span-4"><p class="org-eyebrow">The Hey King journey</p><h3>Application → relationship</h3><div class="org-timeline"><div class="org-timeline-item"><small>1</small><strong>Application & eligibility</strong><p>Capture need, referral, timing, and transportation.</p></div><div class="org-timeline-item"><small>2</small><strong>Appointment & measurements</strong><p>Reusable fitting profile with history.</p></div><div class="org-timeline-item"><small>3</small><strong>Outfit & fulfillment</strong><p>Reserve pieces, alterations, pickup, distribution.</p></div><div class="org-timeline-item"><small>4</small><strong>Mentorship opportunity</strong><p>Match young men into intentional relationship.</p></div><div class="org-timeline-item"><small>5</small><strong>Goals & milestones</strong><p>Track growth beyond the suit.</p></div></div></aside>
        <article class="org-surface org-pad org-span-7"><header class="org-section-head"><div><p class="org-eyebrow">Inventory intelligence</p><h2>What Hey King needs right now</h2></div><button class="org-button" type="button" (click)="section.set('inventory')">Inventory</button></header><div class="org-list"><div class="org-list-row"><div><strong>HIGH · 44R–48R navy/charcoal suits</strong><p>Demand is outpacing ready stock for active applications.</p></div><span class="org-status org-status--bad">High</span></div><div class="org-list-row"><div><strong>HIGH · Size 11–13 black dress shoes</strong><p>Three upcoming appointments need larger shoe availability.</p></div><span class="org-status org-status--bad">High</span></div><div class="org-list-row"><div><strong>MEDIUM · 17–18 neck white shirts</strong><p>Core professional wardrobe staple.</p></div><span class="org-status org-status--warn">Medium</span></div><div class="org-list-row"><div><strong>LOW · Ties</strong><p>Current stock is healthy.</p></div><span class="org-status org-status--good">Low</span></div></div></article>
        <aside class="org-surface org-pad org-span-5"><p class="org-eyebrow">Platform connections</p><h3>Shared system, clear ownership</h3><div class="org-module-links"><a class="org-module-link" [href]="product.peopleUrl"><strong>People</strong><span>One person record</span></a><a class="org-module-link" [href]="product.operationsUrl"><strong>Operations</strong><span>Fulfillment work</span></a><a class="org-module-link" [href]="product.careUrl"><strong>Care</strong><span>Sensitive pastoral needs</span></a><a class="org-module-link" [href]="product.academyUrl"><strong>Academy</strong><span>Mentor resources</span></a><a class="org-module-link" [href]="product.impactUrl"><strong>Impact</strong><span>Outcomes & health</span></a></div></aside></div>
      }
      @case('applications'){
        <article class="org-surface org-pad"><header class="org-section-head"><div><p class="org-eyebrow">Recipient intake</p><h2>Applications</h2><p>Move each request through review, approval, scheduling, service, and follow-up with a visible state.</p></div></header><div class="org-table-wrap"><table class="org-table"><thead><tr><th>Applicant</th><th>Need</th><th>Referral</th><th>Event / deadline</th><th>Transportation</th><th>Status</th></tr></thead><tbody>@for(a of state().applications;track a.id){<tr data-clickable (click)="openApplication(a.id)"><td><strong>{{a.name}}</strong><br><small>{{a.phone}}</small></td><td>{{a.need}}</td><td>{{a.referral}}</td><td>{{a.eventDate}}</td><td>{{a.transportation}}</td><td><span class="org-status" [class.org-status--good]="a.status==='Approved'" [class.org-status--warn]="a.status==='Under Review'||a.status==='Need More Information'">{{a.status}}</span></td></tr>}</tbody></table></div></article>
      }
      @case('recipients'){
        <div class="org-card-grid">@for(r of state().recipients;track r.id){<article class="org-card"><div class="org-profile"><span class="org-avatar">{{initials(r.name)}}</span><div><h3>{{r.name}}</h3><p>{{r.status}} · {{r.referral}}</p></div></div><p><strong>Need:</strong> {{r.need}}<br><strong>Next:</strong> {{r.nextAppointment}}</p><div class="org-chip-row"><span class="org-chip">{{r.measurements.length?'Measurements on file':'Measurements needed'}}</span><span class="org-chip">{{r.outfitId?'Outfit linked':'Outfit needed'}}</span><span class="org-chip">{{r.mentorshipId?'Mentorship active':'Mentorship optional'}}</span></div><footer><span>{{r.timeline.length}} timeline events</span><button class="org-button" type="button" (click)="openRecipient(r.id)">Open</button></footer></article>}</div>
      }
      @case('appointments'){
        <article class="org-surface org-pad"><header class="org-section-head"><div><p class="org-eyebrow">Schedule</p><h2>Appointments</h2><p>Intake, measurements, fitting, alteration, pickup, and follow-up stay tied to the recipient.</p></div></header><div class="org-list">@for(a of state().appointments;track a.id){<div class="org-list-row"><div><strong>{{a.date}} · {{a.time}} · {{recipientName(a.recipientId)}}</strong><p>{{a.type}} · Owner: {{a.owner}} · {{a.notes}}</p></div><div class="org-actions"><span class="org-status">{{a.status}}</span><button class="org-button" type="button" (click)="completeAppointment(a.id)">{{a.status==='Completed'?'Completed':'Complete'}}</button></div></div>}</div></article>
      }
      @case('inventory'){
        <div class="org-grid"><article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">Suit Operations</p><h2>Inventory</h2><p>Enough structure to know what is available, reserved, assigned, cleaning, altered, distributed, or retired.</p></div></header><div class="org-table-wrap"><table class="org-table"><thead><tr><th>Item</th><th>Size</th><th>Color</th><th>Condition</th><th>Source</th><th>Status</th></tr></thead><tbody>@for(i of state().inventory;track i.id){<tr><td><strong>{{i.category}}</strong></td><td>{{i.size}}</td><td>{{i.color}}</td><td>{{i.condition}}</td><td>{{i.source}}</td><td><span class="org-status" [class.org-status--good]="i.status==='Available'">{{i.status}}</span></td></tr>}</tbody></table></div></article><aside class="org-surface org-pad org-span-4"><p class="org-eyebrow">Needs forecast</p><h3>Turn demand into donor guidance</h3><div class="org-list"><div class="org-list-row"><div><strong>44R–48R suits</strong><p>Navy / charcoal</p></div><span class="org-status org-status--bad">High</span></div><div class="org-list-row"><div><strong>11–13 shoes</strong><p>Black dress</p></div><span class="org-status org-status--bad">High</span></div><div class="org-list-row"><div><strong>17–18 shirts</strong><p>White</p></div><span class="org-status org-status--warn">Medium</span></div></div><button class="org-button org-button--primary" style="margin-top:14px" type="button" (click)="section.set('portal')">Preview public needs</button></aside></div>
      }
      @case('outfits'){
        <div class="org-card-grid">@for(o of state().outfits;track o.id){<article class="org-card"><p class="org-eyebrow">{{recipientName(o.recipientId)}}</p><h3>{{o.name}}</h3><p>Status: {{o.status}}<br>Alterations: {{o.alterationStatus}}</p><div class="org-list">@for(item of o.items;track item.label){<div class="org-list-row"><div><strong>{{item.label}}</strong></div><span>{{item.inventoryId?'✓':'○'}}</span></div>}</div><footer><span>{{outfitReady(o)}} required pieces ready</span><button class="org-button" type="button" (click)="advanceOutfit(o.id)">Advance status</button></footer></article>}</div>
      }
      @case('partners'){
        <div class="org-grid"><article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">Relationship network</p><h2>Partners</h2><p>Tailors, donors, employers, workforce organizations, churches, community organizations, and referral sources.</p></div></header><div class="org-card-grid">@for(p of state().partners;track p.id){<article class="org-card"><p class="org-eyebrow">{{p.type}}</p><h3>{{p.name}}</h3><p>{{p.contact}} · {{p.email}}<br>{{p.notes}}</p><footer><span>{{p.referrals? p.referrals+' referrals':p.completed+' completed'}} · {{p.turnaround}}</span><span class="org-status org-status--good">Active</span></footer></article>}</div></article><aside class="org-surface org-pad org-span-4"><header class="org-section-head"><div><p class="org-eyebrow">Transactions</p><h3>Inventory + service history</h3></div><button class="org-button org-button--primary" type="button" (click)="recordDemoTransaction()">Record transaction</button></header><div class="org-list">@for(t of state().transactions;track t.id){<div class="org-list-row"><div><strong>{{t.type}} · {{t.description}}</strong><p>{{t.date}} · {{t.partner}} · {{t.recipient}}</p></div><span class="org-status">{{t.value}}</span></div>}</div></aside></div>
      }
      @case('mentorship'){
        <div class="org-grid"><article class="org-surface org-pad org-span-12"><div class="org-metrics"><div class="org-metric"><span>Active mentees</span><strong>{{activeMentorships()}}</strong><small>1-to-1 relationships</small></div><div class="org-metric"><span>Pastor Hickman</span><strong>{{mentorById('mentor1')?.active}} / {{mentorById('mentor1')?.capacity}}</strong><small>Active / capacity</small></div><div class="org-metric"><span>Goals in progress</span><strong>{{goalsInProgress()}}</strong><small>Across all mentees</small></div><div class="org-metric"><span>Meetings logged</span><strong>{{meetingsLogged()}}</strong><small>Mentorship history</small></div><div class="org-metric"><span>Cohorts</span><strong>{{state().cohorts.length}}</strong><small>Group mentoring</small></div></div></article>
        <article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">Pastor Hickman's dashboard</p><h2>My mentees</h2><p>Track meetings, goals, follow-up, milestones, and the next intentional conversation.</p></div></header><div class="org-table-wrap"><table class="org-table"><thead><tr><th>Young man</th><th>Last meeting</th><th>Cadence</th><th>Focus</th><th>Goals</th><th>Status</th></tr></thead><tbody>@for(m of state().mentorships;track m.id){<tr data-clickable (click)="openMentorship(m.id)"><td><strong>{{recipientName(m.menteeId)}}</strong></td><td>{{lastMeeting(m)}}</td><td>{{m.cadence}}</td><td>{{m.focus.join(', ')}}</td><td>{{completedGoals(m)}} / {{m.goals.length}}</td><td><span class="org-status org-status--good">{{m.status}}</span></td></tr>}</tbody></table></div></article>
        <aside class="org-surface org-pad org-span-4"><p class="org-eyebrow">Mentor capacity</p><h3>Healthy matching</h3><div class="org-list">@for(m of state().mentors;track m.id){<div class="org-list-row"><div><strong>{{m.name}}</strong><p>{{m.focus.join(' · ')}}</p><div class="org-progress" style="margin-top:7px"><span [style.width.%]="m.active*100/m.capacity"></span></div></div><span>{{m.active}} / {{m.capacity}}</span></div>}</div></aside>
        <article class="org-surface org-pad org-span-7"><p class="org-eyebrow">Cohorts</p><h2>Brotherhood cohorts</h2>@for(c of state().cohorts;track c.id){<div class="org-callout"><strong>{{c.name}}</strong><br>{{c.leader}} · {{c.members.length}} young men<br><span>{{c.topics.join(' · ')}}</span></div>}</article><aside class="org-surface org-pad org-span-5"><p class="org-eyebrow">Privacy design</p><h3>Three levels of mentorship information</h3><div class="org-list"><div class="org-list-row"><div><strong>General mentorship notes</strong><p>Authorized program leaders can coordinate.</p></div></div><div class="org-list-row"><div><strong>Private mentor note</strong><p>Visible only to the mentor where appropriate.</p></div></div><div class="org-list-row"><div><strong>Sensitive pastoral issue</strong><p>Escalates to Care; Engagements receives status only.</p></div><a class="org-link" [href]="product.careUrl">Care ↗</a></div></div></aside></div>
      }
      @case('volunteers'){
        <div class="org-grid"><article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">Saturday Distribution Day</p><h2>Volunteer assignments</h2><p>Reusable assignment patterns for intake, measurements, styling, inventory, hospitality, and media.</p></div></header><div class="org-list">@for(v of state().volunteers;track v.id){<div class="org-list-row"><div><strong>{{v.role}}</strong><p>{{v.event}} · {{v.date}}</p></div><div class="org-actions"><span class="org-status" [class.org-status--warn]="!v.owner">{{v.owner||'Needs owner'}}</span>@if(!v.owner){<button class="org-button org-button--primary" type="button" (click)="assignVolunteer(v.id)">Assign Sarah</button>}</div></div>}</div></article><aside class="org-surface org-pad org-span-4"><p class="org-eyebrow">People matching</p><h3>Skills → opportunity</h3><p class="org-callout">People can hold skills and interests such as styling, tailoring, hospitality, photography, interviewing, transportation, administration, and mentoring. Engagements can recommend opportunities without duplicating the People profile.</p><a class="org-button" style="margin-top:12px" [href]="product.peopleUrl">Open People</a></aside></div>
      }
      @case('impact'){
        <div class="org-grid"><article class="org-surface org-pad org-span-8"><header class="org-section-head"><div><p class="org-eyebrow">2027 impact story</p><h2>Measure the ministry beyond distribution</h2></div><a class="org-link" [href]="product.impactUrl">Open Impact ↗</a></header><div class="org-metrics"><div class="org-metric"><span>Men served</span><strong>186</strong></div><div class="org-metric"><span>Complete outfits</span><strong>164</strong></div><div class="org-metric"><span>Interview requests</span><strong>72</strong></div><div class="org-metric"><span>Employment milestones</span><strong>38</strong></div><div class="org-metric"><span>Active partners</span><strong>24</strong></div></div><div class="org-card-grid" style="margin-top:14px"><div class="org-card"><h3>Mentorship depth</h3><p>31 enrolled · 24 active relationships · 7 completed cycles.</p></div><div class="org-card"><h3>Leadership multiplication</h3><p>11 serving in community · 6 emerging leaders.</p></div><div class="org-card"><h3>Stewardship</h3><p>$42,800 estimated clothing value distributed.</p></div></div></article><aside class="org-surface org-pad org-span-4"><p class="org-eyebrow">Operational analytics</p><h3>Questions ApostolOS can answer</h3><div class="org-list"><div class="org-list-row"><div><strong>Which sizes are always scarce?</strong><p>Inventory need by active application demand.</p></div></div><div class="org-list-row"><div><strong>How long from application to fulfillment?</strong><p>Cycle time by referral source and need.</p></div></div><div class="org-list-row"><div><strong>Who entered ongoing relationship?</strong><p>Fulfillment → mentorship conversion.</p></div></div><div class="org-list-row"><div><strong>What changed after service?</strong><p>Employment, service, leadership, and follow-up milestones.</p></div></div></div></aside></div>
      }
      @case('portal'){
        <div class="org-grid"><article class="org-surface org-pad org-span-6"><p class="org-eyebrow">Recipient experience</p><h2>My Hey King</h2><div class="org-portal-phone"><div class="org-portal-phone__screen"><header class="org-portal-phone__head"><small>Hey King</small><h2>Welcome, Marcus</h2><p>Your next step is ready.</p></header><div class="org-portal-phone__body"><article><small>Next appointment</small><strong>September 14 · 2:00 PM</strong><p>Alteration fitting · bring the shoes you plan to wear.</p></article><article><small>Your outfit</small><strong>5 of 5 required pieces ready</strong><p>Navy suit · white shirt · blue tie · black belt · black shoes. Alterations in progress.</p></article><article><small>Your mentorship</small><strong>Pastor Hickman</strong><p>Next focus: interview preparation, prayer, and résumé follow-up.</p></article><article><small>Current goals</small><strong>4 active goals</strong><p>Résumé · interview · prayer rhythm · serve at a distribution day.</p></article></div></div></div></article><aside class="org-surface org-pad org-span-6"><p class="org-eyebrow">Public + partner entry points</p><h2>Website-connected workflows</h2><div class="org-card-grid"><article class="org-card"><h3>Apply for Assistance</h3><p>Public application enters the governed recipient pipeline.</p></article><article class="org-card"><h3>Donate Clothing</h3><p>Publish current inventory needs instead of a generic donation list.</p></article><article class="org-card"><h3>Refer a Client</h3><p>Partner portal sees referral status without private measurements or notes.</p></article><article class="org-card"><h3>Become a Partner</h3><p>Capture tailoring, employment, church, donor, and community relationships.</p></article><article class="org-card"><h3>Volunteer</h3><p>Match People skills to distribution, styling, transport, and mentorship needs.</p></article><article class="org-card"><h3>My Appointment</h3><p>Recipient-safe status, preparation, directions, and contact.</p></article></div><div class="org-callout" style="margin-top:14px"><strong>Referral portal boundary:</strong> a partner can submit a referral and see received, scheduled, and completed status. They cannot see private measurements, internal mentorship notes, or Care records.</div></aside></div>
      }
    }

    @if(selectedApplication();as a){<button class="org-drawer-scrim" type="button" (click)="applicationId.set(null)" aria-label="Close application"></button><aside class="org-drawer"><header><div><p>Application · {{a.status}}</p><h2>{{a.name}}</h2></div><button class="org-close" type="button" (click)="applicationId.set(null)">×</button></header><div class="org-drawer__body"><div class="org-form-grid"><div class="org-callout"><strong>Need</strong><br>{{a.need}}</div><div class="org-callout"><strong>Deadline</strong><br>{{a.eventDate}}</div><div class="org-callout"><strong>Referral</strong><br>{{a.referral}}</div><div class="org-callout"><strong>Transportation</strong><br>{{a.transportation}}</div></div><p class="org-eyebrow" style="margin-top:18px">Contact & review</p><p>{{a.phone}} · {{a.email}}<br>{{a.availability}}<br>{{a.note}}</p><div class="org-actions"><button class="org-button" type="button" (click)="setApplicationStatus(a.id,'Need More Information')">Need info</button><button class="org-button" type="button" (click)="setApplicationStatus(a.id,'Waitlisted')">Waitlist</button><button class="org-button org-button--primary" type="button" (click)="approveApplication(a.id)">Approve & create recipient</button></div></div></aside>}

    @if(selectedRecipient();as r){<button class="org-drawer-scrim" type="button" (click)="recipientId.set(null)" aria-label="Close recipient"></button><aside class="org-drawer"><header><div><p>{{r.status}}</p><h2>{{r.name}}</h2></div><button class="org-close" type="button" (click)="recipientId.set(null)">×</button></header><div class="org-drawer__body"><div class="org-drawer-tabs">@for(t of recipientTabs;track t){<button type="button" [class.active]="recipientTab()===t" (click)="recipientTab.set(t)">{{t}}</button>}</div>@switch(recipientTab()){@case('journey'){<div class="org-callout"><strong>Next:</strong> {{r.nextAppointment}}</div><div class="org-timeline">@for(e of r.timeline;track e.date+e.title){<div class="org-timeline-item"><small>{{e.date}}</small><strong>{{e.title}}</strong><p>{{e.detail}}</p></div>}</div>}@case('measurements'){@if(r.measurements.length){@for(m of r.measurements;track m.date){<div class="org-callout" style="margin-bottom:10px"><strong>{{m.date}}</strong><br>Jacket {{m.jacket}} · Sleeve {{m.sleeve}} · Neck {{m.neck}} / {{m.shirtSleeve}} · Waist {{m.waist}} · Inseam {{m.inseam}} · Shoe {{m.shoe}}<br><small>{{m.notes}}</small></div>}}@else{<div class="org-empty">Measurements have not been recorded yet.</div>}}@case('outfit'){@if(r.outfitId&&outfitById(r.outfitId);as o){<h3>{{o.name}}</h3><p>{{o.status}} · {{o.alterationStatus}}</p><div class="org-list">@for(item of o.items;track item.label){<div class="org-list-row"><div><strong>{{item.label}}</strong></div><span>{{item.inventoryId?'✓':'○'}}</span></div>}</div>}@else{<div class="org-empty">No outfit assigned yet.</div>}}@case('mentorship'){@if(r.mentorshipId){<button class="org-button org-button--primary" type="button" (click)="openMentorshipFromRecipient(r.mentorshipId)">Open mentorship relationship</button>}@else{<div class="org-callout">Mentorship is an invitation, not an automatic requirement. This recipient has not been matched.</div>}}}</div></aside>}

    @if(selectedMentorship();as m){<button class="org-drawer-scrim" type="button" (click)="mentorshipId.set(null)" aria-label="Close mentorship"></button><aside class="org-drawer"><header><div><p>{{m.program}} · {{m.status}}</p><h2>{{recipientName(m.menteeId)}}</h2></div><button class="org-close" type="button" (click)="mentorshipId.set(null)">×</button></header><div class="org-drawer__body"><div class="org-profile"><span class="org-avatar">{{initials(recipientName(m.menteeId))}}</span><div><h3>{{mentorName(m.mentorId)}} → {{recipientName(m.menteeId)}}</h3><p>{{m.cadence}} · Started {{m.started}}</p></div></div><div class="org-chip-row" style="margin:14px 0">@for(f of m.focus;track f){<span class="org-chip">{{f}}</span>}</div><div class="org-drawer-tabs">@for(t of mentorshipTabs;track t){<button type="button" [class.active]="mentorshipTab()===t" (click)="mentorshipTab.set(t)">{{t}}</button>}</div>@switch(mentorshipTab()){@case('meetings'){<div class="org-list">@for(meeting of m.meetings;track meeting.id){<div class="org-list-row"><div><strong>{{meeting.date}} · {{meeting.duration}}</strong><p>{{meeting.topics.join(' · ')}}<br>{{meeting.note}}</p><small>Privacy: {{meeting.privacy}} · Follow-up: {{meeting.followUps.join(' · ')}}</small></div></div>}</div><button class="org-button org-button--primary" style="margin-top:12px" type="button" (click)="logDemoMeeting(m.id)">Log mentorship meeting</button>}@case('goals'){<div>@for(g of m.goals;track g.id){<div class="org-goal"><div class="org-goal__top"><strong>{{g.category}} · {{g.title}}</strong><button class="org-button" type="button" (click)="toggleGoal(m.id,g.id)">{{g.status}}</button></div><p>Due {{g.due}} · Resource: {{g.resource}}</p></div>}</div>}@case('milestones'){<div class="org-timeline">@for(ms of m.milestones;track ms.date+ms.title){<div class="org-timeline-item"><small>{{ms.date}}</small><strong>{{ms.title}}</strong><p>{{ms.detail}}</p></div>}</div>}@case('privacy'){<div class="org-callout"><strong>General mentorship notes</strong><br>Visible to authorized mentorship leaders for coordination.</div><div class="org-callout" style="margin-top:9px"><strong>Private mentor note</strong><br>Can be restricted to the assigned mentor.</div><div class="org-callout" style="margin-top:9px"><strong>Sensitive pastoral issue</strong><br>Send to Care. Engagements keeps only the handoff status, not the confidential narrative.</div><a class="org-button" style="margin-top:12px" [href]="product.careUrl">Open Care</a>}}</div></aside>}
  </section>`,
  styleUrl:'./organization-space.scss'
})
export class HeyyKingSpaceComponent{
  @Input({required:true}) product!:ProductInfo;
  readonly tabs=[{key:'overview',label:'Overview'},{key:'applications',label:'Applications'},{key:'recipients',label:'Recipients'},{key:'appointments',label:'Appointments'},{key:'inventory',label:'Inventory'},{key:'outfits',label:'Outfits'},{key:'partners',label:'Partners'},{key:'mentorship',label:'Mentorship'},{key:'volunteers',label:'Volunteers'},{key:'impact',label:'Impact'},{key:'portal',label:'Portals'}] as const;
  readonly recipientTabs=['journey','measurements','outfit','mentorship'] as const;
  readonly mentorshipTabs=['meetings','goals','milestones','privacy'] as const;
  readonly section=signal<string>('overview');
  readonly state=signal<HkState>(this.load());
  readonly applicationId=signal<string|null>(null);
  readonly recipientId=signal<string|null>(null);
  readonly mentorshipId=signal<string|null>(null);
  readonly recipientTab=signal<string>('journey');
  readonly mentorshipTab=signal<string>('meetings');

  private load():HkState{try{const raw=localStorage.getItem('apostolos.engagements.heyyking.v1');return raw?JSON.parse(raw) as HkState:structuredClone(SEED);}catch{return structuredClone(SEED)}}
  private persist(next:HkState){this.state.set(next);try{localStorage.setItem('apostolos.engagements.heyyking.v1',JSON.stringify(next));}catch{}}
  openApplications(){return this.state().applications.filter(a=>!['Completed','Declined'].includes(a.status)).length}
  activeOutfits(){return this.state().outfits.filter(o=>o.status!=='Distributed').length}
  activeMentorships(){return this.state().mentorships.filter(m=>m.status==='Active').length}
  goalsInProgress(){return this.state().mentorships.flatMap(m=>m.goals).filter(g=>g.status==='In Progress').length}
  meetingsLogged(){return this.state().mentorships.reduce((s,m)=>s+m.meetings.length,0)}
  initials(name:string){return name.split(' ').map(p=>p[0]).slice(0,2).join('').toUpperCase()}
  recipientName(id:string){return this.state().recipients.find(r=>r.id===id)?.name??NAMES[0]}
  mentorName(id:string){return this.state().mentors.find(m=>m.id===id)?.name??'Mentor'}
  mentorById(id:string){return this.state().mentors.find(m=>m.id===id)}
  outfitById(id:string){return this.state().outfits.find(o=>o.id===id)}
  outfitReady(o:Outfit){const required=o.items.filter(i=>i.required);return `${required.filter(i=>i.inventoryId).length} of ${required.length}`}
  selectedApplication(){const id=this.applicationId();return id?this.state().applications.find(a=>a.id===id):undefined}
  selectedRecipient(){const id=this.recipientId();return id?this.state().recipients.find(r=>r.id===id):undefined}
  selectedMentorship(){const id=this.mentorshipId();return id?this.state().mentorships.find(m=>m.id===id):undefined}
  openApplication(id:string){this.applicationId.set(id)}
  openRecipient(id:string){this.recipientId.set(id);this.recipientTab.set('journey')}
  openMentorship(id:string){this.mentorshipId.set(id);this.mentorshipTab.set('meetings')}
  openMentorshipFromRecipient(id:string){this.recipientId.set(null);this.openMentorship(id)}
  setApplicationStatus(id:string,status:string){const next=structuredClone(this.state());const a=next.applications.find(x=>x.id===id);if(a){a.status=status;this.persist(next)}}
  approveApplication(id:string){const next=structuredClone(this.state());const a=next.applications.find(x=>x.id===id);if(!a)return;a.status='Approved';if(!next.recipients.some(r=>r.name===a.name)){next.recipients.push({id:`recipient-${Date.now()}`,name:a.name,status:'Active Recipient',referral:a.referral,need:a.need,nextAppointment:'Scheduling required',measurements:[],outfitId:null,mentorshipId:null,timeline:[{date:'Today',title:'Approved',detail:'Application approved and recipient record created.'}]})}this.persist(next);this.applicationId.set(null);this.section.set('recipients')}
  completeAppointment(id:string){const next=structuredClone(this.state());const a=next.appointments.find(x=>x.id===id);if(a){a.status='Completed';const r=next.recipients.find(x=>x.id===a.recipientId);if(r)r.timeline.unshift({date:'Today',title:`${a.type} completed`,detail:a.notes});this.persist(next)}}
  advanceOutfit(id:string){const next=structuredClone(this.state());const o=next.outfits.find(x=>x.id===id);if(!o)return;const order=['Assigned','Alterations','Ready for Pickup','Distributed'];const i=Math.max(0,order.indexOf(o.status));o.status=order[Math.min(i+1,order.length-1)];if(o.status==='Distributed'){for(const item of o.items){const inv=next.inventory.find(x=>x.id===item.inventoryId);if(inv)inv.status='Distributed'}const r=next.recipients.find(x=>x.id===o.recipientId);r?.timeline.unshift({date:'Today',title:'Outfit distributed',detail:`${o.name} fulfillment completed.`})}this.persist(next)}
  recordDemoTransaction(){const next=structuredClone(this.state());next.transactions.unshift({id:`tx-${Date.now()}`,date:'Today',type:'Inventory receipt',description:'12 navy and charcoal suits received',partner:'Menswear Community Partner',recipient:'—',value:'12 items'});this.persist(next)}
  assignVolunteer(id:string){const next=structuredClone(this.state());const v=next.volunteers.find(x=>x.id===id);if(v){v.owner='Sarah Jones';v.status='Assigned';this.persist(next)}}
  lastMeeting(m:Mentorship){return m.meetings.length?m.meetings[m.meetings.length-1].date:'Not yet'}
  completedGoals(m:Mentorship){return m.goals.filter(g=>g.status==='Completed').length}
  toggleGoal(mentorshipId:string,goalId:string){const next=structuredClone(this.state());const g=next.mentorships.find(m=>m.id===mentorshipId)?.goals.find(x=>x.id===goalId);if(g){g.status=g.status==='Completed'?'In Progress':'Completed';this.persist(next)}}
  logDemoMeeting(id:string){const next=structuredClone(this.state());const m=next.mentorships.find(x=>x.id===id);if(!m)return;m.meetings.push({id:`meeting-${Date.now()}`,date:'Today',duration:'45 min',topics:['Prayer','Employment','Personal goals'],note:'Reviewed current goals, celebrated progress, and agreed on the next concrete step.',privacy:'Mentorship team',followUps:['Check in after next milestone']});m.milestones.push({date:'Today',title:'Mentorship meeting completed',detail:'Progress reviewed and next step agreed.'});this.persist(next)}
}
