import { Component, EventEmitter, Input, Output, signal } from '@angular/core';
import { forkJoin } from 'rxjs';
import { EngagementsApiService } from '../../core/engagements-api.service';
import {
  AssignmentWorkspaceDetails,
  EngagementDetails,
  HostCoordinationDocument,
} from '../../core/models';

@Component({
  selector: 'app-documents-tab',
  standalone: true,
  template: `
    <section class="documents-workspace">
      <header>
        <div>
          <p>Record · Documents</p>
          <h2>Assignment documents</h2>
          <span>Agreements, host files, itineraries, and preparation records stay connected to this assignment.</span>
        </div>
        <label class="upload-button">
          <input type="file" [disabled]="saving()" (change)="upload($event)" />
          {{ saving() ? 'Uploading…' : '＋ Add document' }}
        </label>
      </header>

      @if (message()) { <div class="message">{{ message() }}<button type="button" aria-label="Dismiss message" (click)="message.set(null)">×</button></div> }
      @if (error()) { <div class="message error">{{ error() }}<button type="button" aria-label="Dismiss error" (click)="error.set(null)">×</button></div> }

      <section class="document-group">
        <div class="group-heading">
          <div><p>Host coordination files</p><span>Files supplied during preparation and coordination.</span></div>
          <strong>{{ workspace.preparation.coordination.documents.length }}</strong>
        </div>
        @if (workspace.preparation.coordination.documents.length === 0) {
          <div class="empty">No host coordination files have been uploaded.</div>
        } @else {
          <div class="document-list">
            @for (document of workspace.preparation.coordination.documents; track document.id) {
              <article>
                <span class="file-icon">DOC</span>
                <div class="file-record">
                  <a [href]="workspaceDocumentUrl(document.id)" target="_blank" rel="noopener"><strong>{{ document.fileName }}</strong></a>
                  <small>{{ fileSize(document.length) }} · {{ dateLabel(document.uploadedAtUtc) }} · {{ document.contentType }}</small>
                </div>
                <details class="file-menu">
                  <summary aria-label="Document actions">•••</summary>
                  <button type="button" [disabled]="saving()" (click)="remove(document)">Remove document</button>
                </details>
              </article>
            }
          </div>
        }
      </section>

      <section class="document-group">
        <div class="group-heading">
          <div><p>Assignment record</p><span>Linked records generated by the engagement lifecycle.</span></div>
          <strong>{{ assignment.documents.length }}</strong>
        </div>
        @if (assignment.documents.length === 0) {
          <div class="empty">No assignment record documents are listed.</div>
        } @else {
          <div class="record-list">
            @for (document of assignment.documents; track document.id) {
              <a class="record-document" [href]="recordDocumentUrl(document.id)" target="_blank" rel="noopener">
                <span class="record-type">{{ document.category }}</span>
                <div><strong>{{ document.name }}</strong><small>{{ dateLabel(document.updatedAtUtc) }}</small></div>
                <span class="record-status">{{ document.status.replace('-', ' ') }}</span>
              </a>
            }
          </div>
        }
      </section>

      @if (pendingRemoval(); as document) {
        <button class="modal-scrim" type="button" aria-label="Cancel removal" (click)="pendingRemoval.set(null)"></button>
        <section class="confirm-modal" role="alertdialog" aria-modal="true" aria-labelledby="remove-document-title">
          <header><div><p>Assignment document</p><h2 id="remove-document-title">Remove {{ document.fileName }}?</h2></div><button type="button" aria-label="Close" (click)="pendingRemoval.set(null)">×</button></header>
          <p>This removes the file from this assignment. This action cannot be undone.</p>
          <footer><button type="button" class="cancel" (click)="pendingRemoval.set(null)">Cancel</button><button type="button" class="remove" [disabled]="saving()" (click)="confirmRemove()">{{ saving() ? 'Removing…' : 'Remove document' }}</button></footer>
        </section>
      }
    </section>
  `,
  styles: [`
    .documents-workspace{margin-top:1rem;border:1px solid var(--eng-line);border-radius:9px;background:var(--eng-surface);overflow:hidden}
    header{display:flex;justify-content:space-between;gap:1rem;padding:1.15rem 1.3rem;border-bottom:1px solid var(--eng-line)}
    header p,.group-heading p{margin:0 0 .3rem;color:var(--eng-blue);font-size:.65rem;font-weight:900;letter-spacing:.1em;text-transform:uppercase}header h2{margin:0;font-size:1.45rem}header span{display:block;margin-top:.3rem;color:var(--eng-muted);font-size:.73rem}
    .upload-button{display:flex;align-items:center;align-self:start;min-height:36px;padding:.48rem .7rem;border:1px solid var(--eng-line);border-radius:6px;color:var(--eng-ink);background:#fff;font-size:.7rem;font-weight:800;cursor:pointer}.upload-button input{display:none}
    .message{padding:.7rem 1.3rem;color:#25684d;background:#edf7f1;font-size:.73rem;font-weight:750}.message.error{color:var(--eng-danger);background:#fff0ef}
    .document-group{padding:1.1rem 1.2rem;border-bottom:1px solid var(--eng-line)}.document-group:last-child{border-bottom:0}.group-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}.group-heading>div>span{color:var(--eng-muted);font-size:.68rem}.group-heading>strong{color:var(--eng-muted);font-size:.7rem}
    .document-list,.record-list{display:grid;margin-top:.75rem;border-top:1px solid rgba(18,26,44,.09)}.document-list article{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:.7rem;align-items:center;padding:.72rem .15rem;border-bottom:1px solid rgba(18,26,44,.08)}.file-icon{display:grid;width:34px;height:34px;place-items:center;border-radius:6px;color:#315faf;background:#e9effb;font-size:.55rem;font-weight:900}.file-record strong,.file-record small{display:block}.file-record strong{font-size:.78rem}.file-record small{margin-top:.15rem;color:var(--eng-muted);font-size:.63rem}
    .file-menu{position:relative}.file-menu summary{list-style:none;display:grid;width:32px;height:32px;place-items:center;border-radius:6px;color:#687284;cursor:pointer}.file-menu summary::-webkit-details-marker{display:none}.file-menu[open] summary{background:#f0f1f4}.file-menu button{position:absolute;right:0;z-index:2;width:145px;margin-top:.25rem;padding:.5rem .6rem;border:1px solid #e2c3c1;border-radius:6px;color:#a34742;background:#fff;font-size:.68rem;font-weight:800;box-shadow:0 8px 22px rgba(18,26,44,.1);cursor:pointer}
    .record-list article{display:grid;grid-template-columns:120px minmax(0,1fr) auto;align-items:center;gap:.8rem;padding:.72rem .15rem;border-bottom:1px solid rgba(18,26,44,.08)}.record-type{color:var(--eng-blue);font-size:.59rem;font-weight:900;text-transform:uppercase}.record-list strong,.record-list small{display:block}.record-list strong{font-size:.76rem}.record-list small{margin-top:.14rem;color:var(--eng-muted);font-size:.61rem}.record-status{color:#667080;font-size:.65rem;font-weight:750;text-transform:capitalize}.empty{margin-top:.7rem;padding:.9rem;color:var(--eng-muted);background:#faf9f7;text-align:center;font-size:.72rem}
    @media(max-width:620px){header{display:grid}.upload-button{justify-self:start}.record-list article{grid-template-columns:1fr auto}.record-type{grid-column:1/-1}}
  `, `
    .message{display:flex;align-items:center;justify-content:space-between;gap:1rem}.message button{width:28px;height:28px;border:0;border-radius:50%;color:inherit;background:rgba(255,255,255,.65);font-size:1rem;cursor:pointer}
    .file-record a{color:inherit;text-decoration:none}.file-record a:hover{text-decoration:underline}
    .record-document{display:grid;grid-template-columns:120px minmax(0,1fr) auto;align-items:center;gap:.8rem;padding:.72rem .15rem;border-bottom:1px solid rgba(18,26,44,.08);color:inherit;text-decoration:none}.record-document:hover{background:#fafbfc}
    .modal-scrim{position:fixed;inset:0;z-index:70;border:0;background:rgba(12,18,32,.38);backdrop-filter:blur(3px)}
    .confirm-modal{position:fixed;z-index:71;left:50%;top:50%;width:min(480px,calc(100vw - 32px));padding:1.25rem;border-radius:14px;background:#fff;box-shadow:0 28px 90px rgba(15,23,42,.28);transform:translate(-50%,-50%)}
    .confirm-modal header{padding:0 0 1rem}.confirm-modal header p{margin:0;color:var(--eng-blue);font-size:.64rem;font-weight:900;text-transform:uppercase}.confirm-modal header h2{margin:.3rem 0 0}.confirm-modal header>button{width:38px;height:38px;border:0;border-radius:8px;font-size:1.15rem}.confirm-modal>p{color:var(--eng-muted);line-height:1.55}.confirm-modal footer{display:flex;justify-content:flex-end;gap:.6rem;margin-top:1.2rem}.confirm-modal footer button{min-height:40px;padding:0 .85rem;border-radius:7px;font-weight:800}.confirm-modal .cancel{border:1px solid var(--eng-line);background:#fff}.confirm-modal .remove{border:1px solid #a44843;color:#fff;background:#a44843}
    @media(max-width:620px){.record-document{grid-template-columns:1fr auto}.record-document .record-type{grid-column:1/-1}}
  `],
})
export class DocumentsTabComponent {
  @Input({ required: true }) assignment!: EngagementDetails;
  @Input({ required: true }) workspace!: AssignmentWorkspaceDetails;
  @Output() assignmentUpdated = new EventEmitter<EngagementDetails>();
  @Output() workspaceUpdated = new EventEmitter<AssignmentWorkspaceDetails>();
  readonly saving = signal(false);
  readonly message = signal<string | null>(null);
  readonly error = signal<string | null>(null);
  readonly pendingRemoval = signal<HostCoordinationDocument | null>(null);

  constructor(private readonly api: EngagementsApiService) {}

  upload(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file || this.saving()) return;
    this.saving.set(true);
    this.error.set(null);
    this.api.uploadWorkspaceDocument(this.assignment.summary.id, file).subscribe({
      next: () => {
        this.refresh('Document uploaded.');
        input.value = '';
      },
      error: () => {
        this.error.set('The document could not be uploaded.');
        this.saving.set(false);
        input.value = '';
      },
    });
  }

  remove(document: HostCoordinationDocument): void {
    if (this.saving()) return;
    this.pendingRemoval.set(document);
  }

  confirmRemove(): void {
    const document = this.pendingRemoval();
    if (!document || this.saving()) return;
    this.saving.set(true);
    this.pendingRemoval.set(null);
    this.error.set(null);
    this.api.deleteWorkspaceDocument(this.assignment.summary.id, document.id).subscribe({
      next: () => this.refresh('Document removed.'),
      error: () => {
        this.error.set('The document could not be removed.');
        this.saving.set(false);
      },
    });
  }

  workspaceDocumentUrl(documentId: string): string { return `/api/engagements/assignments/${encodeURIComponent(this.assignment.summary.id)}/preparation/documents/${encodeURIComponent(documentId)}`; }
  recordDocumentUrl(documentId: string): string { return `/api/engagements/assignments/${encodeURIComponent(this.assignment.summary.id)}/documents/${encodeURIComponent(documentId)}`; }

  fileSize(value: number): string {
    if (value < 1024) return `${value} B`;
    if (value < 1024 * 1024) return `${Math.round(value / 1024)} KB`;
    return `${(value / 1024 / 1024).toFixed(1)} MB`;
  }

  dateLabel(value: string): string {
    return new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
  }

  private refresh(message: string): void {
    forkJoin({
      assignment: this.api.getAssignment(this.assignment.summary.id),
      workspace: this.api.getWorkspace(this.assignment.summary.id),
    }).subscribe({
      next: ({ assignment, workspace }) => {
        this.assignmentUpdated.emit(assignment);
        this.workspaceUpdated.emit(workspace.workspace);
        this.message.set(message);
        this.saving.set(false);
      },
      error: () => {
        this.error.set('The document changed, but the assignment could not be refreshed.');
        this.saving.set(false);
      },
    });
  }
}
